---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: main-mysql-backup-job
  namespace: database
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: "Forbid"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      backoffLimit: 2
      ttlSecondsAfterFinished: 300
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: backup-leantime
              image: vitess/lite:latest
              command: ["sh", "-c", "/vt/bin/vtctldclient BackupShard --server main-mysql-vtctld.database.svc.cluster.local:15999 leantime/-"]
            - name: backup-seafile
              image: vitess/lite:latest
              command: ["sh", "-c", "/vt/bin/vtctldclient BackupShard --server main-mysql-vtctld.database.svc.cluster.local:15999 seafile/-"]
