---
apiVersion: v1
kind: Service
metadata:
  name: main-mysql-vtgate
  namespace: database
spec:
  type: clusterIP
  ports:
    - name: web
      protocol: TCP
      port: 15000
      targetPort: web
    - name: grpc
      protocol: TCP
      port: 15999
      targetPort: grpc
    - name: mysql
      protocol: TCP
      port: 3306
      targetPort: mysql
  selector:
    planetscale.com/cluster: main-mysql
    planetscale.com/component: vtgate
