# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:omcY1AcZobgv4AY8LzVGnsRoB6JlLCcX9tYlwcwrnA3S/UdGB4FwIQ==,iv:V6QC0unzosvCT2wAUsGt/7eaPaHGIGCk9KMty6ybW50=,tag:VNOsVXfOtL+TdelEy6ow4Q==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:xvA4xtYSwfSnab4j79jvJcTP,iv:doIQ8Fm6M+NY1ekaW1++jqttXrEOqsH0Rj9i4u5tqI8=,tag:zkGbHTjPnhfMD6mbaUgV4g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14j28wpn82nnskt0rzcaqxzwnhx33ardgl640rckvwrys8grphvwsyt4ch2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzSkkraW14UThGaVcrRmUy
            eEpzbjBxTFUrRVl4YlZYc3gyM2t6amdVZ2xBCkNRVDJtYWhySHRrOUcxV2gzaitI
            cVRhMTB4U2ZJMmZUUEZVaXB4VjlJMDgKLS0tIEpnc056VGh5Mk1ZUEdZNFkxSGl3
            aUpraEFnVyt1dDZ3WTk0VGVyVHF0aDgKuQeRn1JI6vARRig0deKKgQEDIc/onGEp
            wYvhWYd/DvGIcv/pQNK8pZYAK8Z7aV3hklxMaNhHjU2cz2hM21xaJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-26T04:30:02Z"
    mac: ENC[AES256_GCM,data:c/poviL4wA8LqD7bRjKyoOkKiFWp8h56veRiN7ZgFI2PlmspPHm/b6dvue41w+SUakn1BM0YRrPVrZCCgSAF5M60FrkDqmeqlkge1d7V1lhteVod17e4Tu/RIIUrnDke7Ur2f5C5RdZRsTNsquCCtUcAEOoJ9TVT6KlW2Gd4V08=,iv:BvjMpuwzLLYWJ5k2vZWPT05Cdg81puNR6iU37Ddn+C4=,tag:vBTrv7Yx5vqdKK3vEVPedg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
