---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: database
resources:
  - ./shared-root-secrets.sops.yaml
  - ./shared-root-cluster.yaml
  - ./cluster.yaml
  - ./scheduledbackup.yaml
  - ./prometheusrule.yaml
  - ./service.yaml
  - ./gatus.yaml
