---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
  namespace: minio
spec:
  interval: 15m
  chart:
    spec:
      chart: minio
      version: 5.0.14
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: flux-system
      interval: 15m
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    environment:
      MINIO_SERVER_URL: https://s3.fat-space.com
      MINIO_BROWSER_REDIRECT_URL: https://console.s3.fat-space.com
    mode: standalone
    drivesPerNode: 1
    replicas: 5
    existingSecret: user-secrets
    persistence:
      enabled: true
      storageClass: home-cluster-nfs-1
      accessMode: ReadWriteOnce
      size: 500Gi
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        kubernetes.io/tls-acme: "true"
        kubernetes.io/ingress.allow-http: "false"
        kubernetes.io/ingress.global-static-ip-name: ""
        # nginx.ingress.kubernetes.io/secure-backends: "true"
        # nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        # nginx.ingress.kubernetes.io/whitelist-source-range: 0.0.0.0/0
        cert-manager.io/cluster-issuer: "letsencrypt-production"
        external-dns.alpha.kubernetes.io/target: "ipv4.fat-space.com"
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
        external-dns/is-public: "true"
      path: /
      hosts:
        - &host "s3.fat-space.com"
      tls:
        - secretName: minio-ingress-tls
          hosts:
            - *host
    consoleIngress:
      enabled: true
      ingressClassName: nginx
      annotations:
        kubernetes.io/tls-acme: "true"
        kubernetes.io/ingress.allow-http: "false"
        kubernetes.io/ingress.global-static-ip-name: ""
        # nginx.ingress.kubernetes.io/secure-backends: "true"
        # nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        # nginx.ingress.kubernetes.io/whitelist-source-range: 0.0.0.0/0
        cert-manager.io/cluster-issuer: "letsencrypt-production"
        external-dns.alpha.kubernetes.io/target: "ipv4.fat-space.com"
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
        external-dns/is-public: "true"
      path: /
      hosts:
        - &host "console.s3.fat-space.com"
      tls:
        - secretName: minio-console-ingress-tls
          hosts:
            - *host
    metrics:
      serviceMonitor:
        enabled: true
