---
# yaml-language-server: $schema=https://github.com/fluxcd-community/flux2-schemas/raw/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pgadmin
  namespace: dbms
spec:
  interval: 30m
  chart:
    spec:
      chart: pgadmin4
      version: 1.18.2
      sourceRef:
        kind: HelmRepository
        name: runix
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    nameOverride: pgadmin
    strategy:
      type: Recreate
    env:
      email: ${SECRET_ADMIN_EMAIL}
    existingSecret: pgadmin-secrets
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        hajimari.io/appName: "Postgres Admin"
        hajimari.io/icon: simple-icons:postgresql
      hosts:
        - host: &host pgadmin.${CLUSTER_DOMAIN}
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host
    networkPolicy:
      enabled: false
    persistentVolume:
      enabled: true
      storageClass: ceph-block
      accessModes:
        - ReadWriteOnce
      size: 200Mi
    resources:
      requests:
        cpu: 15m
        memory: 183M
      limits:
        # cpu: 15m
        memory: 283M
