---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vitess-operator
  namespace: database
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    defaultPodOptions:
      priorityClassName: vitess-operator-control-plane
    serviceAccount:
      create: true
      name: vitess-operator
    controllers:
      main:
        containers:
          main:
            image:
              repository: planetscale/vitess-operator
              tag: latest

            command:
              - vitess-operator
            args:
              - --logtostderr
              - -v=4

            env:
              WATCH_NAMESPACE:
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
              POD_NAME:
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
              PS_OPERATOR_POD_NAMESPACE:
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
              PS_OPERATOR_POD_NAME:
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
              OPERATOR_NAME: vitess-operator

            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false

            resources:
              limits:
                memory: 512Mi
              requests:
                cpu: 100m
                memory: 128Mi
    service:
      main:
        enabled: false

    ingress:
      main:
        enabled: false
