ansible_become_pass: ENC[AES256_GCM,data:T+azP4qm0QbTHCy29A==,iv:2p6IZYFMifqElMIbCN3/SssZS8w3NRiInJnKbcKIbXc=,tag:XOw5gcvBz8IYKTWgqKDbtw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14j28wpn82nnskt0rzcaqxzwnhx33ardgl640rckvwrys8grphvwsyt4ch2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5ZnEvQmZtcmtRZHBFdEpJ
            R3lyNjlNV3dBL0VmQkdKa01YenBvK1pjYVFnCnlWbzg1OGVicE9mckpJOElrQk9K
            RkR4NG9yMnQ0N1pGaVFDa2VKU2ZkUjgKLS0tIDJEc3FhZ0hjUk9aRi9rWk52cFZs
            SldXeUhHOWxMMmN3QTF2OTQ2WFpxZWsKgqm73nn3+/N7uu8iEhSfOIMVlZq0BXlg
            RWvy9ikLO5Uyf9FmZ5l+JJ32QtwEToc+qdJTFmef48/Gl+/2IwuWmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-23T08:52:39Z"
    mac: ENC[AES256_GCM,data:4wTjTRVW03PXUfdtnbBpm2F3kuvxSi4UkOINES77SJVZkAKEY/JnBjcZqTF2IVaxPH9g1Mq6zv9O1xBGjnEflGLR1ML0XtQtE+puhT6lBg+S2Cj3XBxmE3fULHMfOnYRl7APUpzwu5Yr2USWGJiRW+LRSOYcxkutCVuYZLyzKG4=,iv:q9o3gTZv8/VEbTK29TsoG0rAKvxS7zxLITo5LCD2ey0=,tag:a5vPkkGXLWL0ACkMedjRzw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
