ansible_become_pass: ENC[AES256_GCM,data:jUvuXbO2Iwk7Kvdi6A==,iv:if4Hrp9Pn8SzylpxzQGBnV6aAzdW5nYn0e5JkjmdM/Y=,tag:ssHRXkMcXKTIBvRR+bYu9Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14j28wpn82nnskt0rzcaqxzwnhx33ardgl640rckvwrys8grphvwsyt4ch2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCQ01PQ1FPZzFTVmUyQ1V1
            dVNkUGVLc01VTHRZYW5WbTNFZnNkOTRGenowCmo2cmtzMVRubDNIbGZ4K1BJQXVC
            RHRwUzNJNExmRnpKMTJncjA4bFpPTlEKLS0tIDVHdnYxb24yREF0Z0RwL2N1SFlE
            cEtQVjYwampRQmZhYXR3STFxNnM3T2sKseklPlQMXF3KVz9BkndpSBcxBROCvSuh
            UnC8kss4+I29zT279mGjtgxBIdjV1eH9iCRX6VDiLSeeH6WmwLq7Sw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-23T23:53:21Z"
    mac: ENC[AES256_GCM,data:BYAV4Bi1eDeNx0+q6G7CAPOsG5fqii2o03/GW+oNaANbQpZRIAcMCzL0AfwUqu1bXKVedGhUgFqc1UE6+MpzqSXR4T3mf7/sv5dAXApoePq6Nx/8DewuV078xPUee7tBCi/C8J1UrZOMF3bhKJSwSbzbPf/oX2Z5/rB5oN/fk3A=,iv:GVwvl9uRX7QS+ko3BIuSZ5kUwBm4hFOjs9ApQ0WncpY=,tag:wesE5p/AUnjzSSRuKbvGNw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
