# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: db-secrets
    namespace: comabase
stringData:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:tutFMWLsfctdU7HUsmXvItVJ,iv:y3OgwG8LDcZ46us0tsGy0ruC8O3f2KhAJSmTMcmrSok=,tag:q0/wzq2e6eqr+Jbh3iWYCw==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:ZwSNyiZpwyV6Vq7z6UQ1N7ApNrsDwV8hFfkkpNjv3gK802gIcGU=,iv:kXxEJik6d0Dn7yYOWzsuTsSEpDqA8aA5RiyX5Fxjbzs=,tag:GB8hpgGf5x8bm8ky1OWnYQ==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:BUunwCtLWRUSwHHaEjrQ/u5J,iv:tt2s1+fzgwZOQzCBm/GgzFJ+qeU+eAsJkmO04A5Gq1A=,tag:HkiPl1YMga/uZ56nU4Mniw==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:0he9/myTgQ/aimZsS+o=,iv:0Ny9xtahupJ49xZWtFGCBGEaXvsjuDPHuvMgdOu2XL4=,tag:eun/CmlKv6Mab0agKxOAAQ==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:VL2Mif7ldc2JDLUFfwJHCw==,iv:84FaQeN+6rL8t2a0pJ9L3zPpjuko621FIPSa9LBhRTI=,tag:PnfYdPdUdZ0Z0QmZ6MFskw==,type:str]
    password: ENC[AES256_GCM,data:S37OxnjNRblfhKQ1GFA=,iv:nR1uwrv7zsRAWD7aBHowmy6nkxRHUmW7rvVNQT7vhZU=,tag:ven0YpBkq21MouK5kk3PEA==,type:str]
    replication-password: ENC[AES256_GCM,data:miGOmHE1VHe7pe5ofcU=,iv:SvHitkAc72cegjfP+YiZquFSS9PyJvskNpRpVBtPE6k=,tag:sRwcNHbABo76LQCmphbc1A==,type:str]
    postgres-password: ENC[AES256_GCM,data:ftjakpVjNBGC6LFt3Mk=,iv:vjQtBvhVEpMKbXjz+QKLuAwTjV889S4dIhsRy2KIlgo=,tag:5d6UVw1PfceQjcFo0rSK7Q==,type:str]
    redis-password: ENC[AES256_GCM,data:WoETu6fjenh7hEg+St8=,iv:SqZmVqiHn33a9KeXbKPLV+DP8cld/n2KVDe1TouMY00=,tag:+rbBbGDHaO8yG3rTQMU9pw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14j28wpn82nnskt0rzcaqxzwnhx33ardgl640rckvwrys8grphvwsyt4ch2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUjQ2NmtLQ1JKVEgwRkdS
            MVZTUnNZWUsvUS9MVWpwb001bXd3L2lJSlhrCkJFajBHNzVobnRWNU5TV2swYnRO
            dEIyNnRpVVVTK01YWU5wZTRPbGN6Y1EKLS0tIGFwYno0aCtybXBLVFc1L2I5VFlB
            eGJtck1sVEVQMi9nZWgvS3hJTm9KWlUKCUUgCNrIGhAfvkFpfoSbyE8y37MS5Bww
            ET2BH5lqLdq35hGdU0jubOFrk4iLyC88x3YEyuIOjrHdf9eCLfQM/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-07T23:40:40Z"
    mac: ENC[AES256_GCM,data:MWS6Kj0Z/4E+6lDf37XFhgP+wVUsnBYINd27P3lSJo4Zv2VhMjYgdgq8Wi24r9GEACVsbK3BJE2A+fpA7eiCQHd0GgxusCqMGsiGRDuvmzngKWDE0+9FYde3JYXVwAVeyilbarMAnYRrmM+1iUTNirmaHOqt06PXXACcZZHLTLc=,iv:lXCacRALF5QCGgeVJiha4752ZERD46MQTwBspa7T/L0=,tag:0GOWguFtkwC69dh3eOpOCQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
