---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-zfs-1
provisioner: nfs.csi.k8s.io
parameters:
  server: 10.0.99.166
  share: /mnt/data/home_cluster_data
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions: ["hard", "noatime"]
