---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-helm-config-values
  namespace: monitoring
data:
  values.yaml: |
    alerting:
      rules.yaml:
        apiVersion: 1
        groups:
          - orgId: 1
            name: Sms Gateways
            folder: IoT
            interval: 1m
            rules:
              - uid: sms_gateway_device_connection_check
                title: Sms Gateway Device Connection
                condition: B
                data:
                  - refId: A
                    relativeTimeRange:
                      from: 600
                      to: 0
                    datasourceUid: prometheus
                    model:
                      disableTextWrap: false
                      editorMode: builder
                      expr: rate(esp_uptime{job="sms_gateway", instance="esp32_475"}[10m])
                      fullMetaSearch: false
                      includeNullMetadata: true
                      instant: true
                      intervalMs: 1000
                      legendFormat: __auto
                      maxDataPoints: 43200
                      range: false
                      refId: A
                      useBackend: false
                  - refId: B
                    relativeTimeRange:
                      from: 600
                      to: 0
                    datasourceUid: __expr__
                    model:
                      conditions:
                        - evaluator:
                            params:
                              - 0
                              - 0
                            type: gt
                          operator:
                            type: and
                          query:
                            params: []
                          reducer:
                            params: []
                            type: avg
                          type: query
                      datasource:
                        name: Expression
                        type: __expr__
                        uid: __expr__
                      expression: $A == 0
                      intervalMs: 1000
                      maxDataPoints: 43200
                      refId: B
                      type: math
                noDataState: NoData
                execErrState: Error
                for: 1m
                annotations:
                  description: ""
                  runbook_url: ""
                  summary: Check connection between SMS Gateway device and prometheus
                labels:
                  "": ""
                isPaused: false
