# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: app-secrets
    namespace: flowise
stringData:
    password: ENC[AES256_GCM,data:S37OxnjNRblfhKQ1GFA=,iv:nR1uwrv7zsRAWD7aBHowmy6nkxRHUmW7rvVNQT7vhZU=,tag:ven0YpBkq21MouK5kk3PEA==,type:str]
    replication-password: ENC[AES256_GCM,data:miGOmHE1VHe7pe5ofcU=,iv:SvHitkAc72cegjfP+YiZquFSS9PyJvskNpRpVBtPE6k=,tag:sRwcNHbABo76LQCmphbc1A==,type:str]
    postgres-password: ENC[AES256_GCM,data:ftjakpVjNBGC6LFt3Mk=,iv:vjQtBvhVEpMKbXjz+QKLuAwTjV889S4dIhsRy2KIlgo=,tag:5d6UVw1PfceQjcFo0rSK7Q==,type:str]
    redis-password: ENC[AES256_GCM,data:WoETu6fjenh7hEg+St8=,iv:SqZmVqiHn33a9KeXbKPLV+DP8cld/n2KVDe1TouMY00=,tag:+rbBbGDHaO8yG3rTQMU9pw==,type:str]
    flowise.username: ENC[AES256_GCM,data:hVjFsg==,iv:BzHnqTStxjFQ526bvrK+iaMRv2NCJQ/w1ljuvQ32iZA=,tag:/XN13Sn5rRvbij/iylHX1A==,type:str]
    flowise.password: ENC[AES256_GCM,data:ZrgHyauy1KEI0fLVxME=,iv:MzlR8rMRjml7aoF9P422BDxLIKArg8g4fgF1ab7aZcU=,tag:QCgC1TuRwgTwXTuP8/Lmww==,type:str]
    flowise.secretkey.overwrite: ENC[AES256_GCM,data:Y0P4Hgx+wwttPYQ/ROLduUU512RnaXjAFd2sw/d47Mc=,iv:o4ylyQ/QxGE8eqGn1sXJoy61Ft3eQeyvydb/3whkCKE=,tag:h7iqT0JU46Cniyo/3UvX/A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14j28wpn82nnskt0rzcaqxzwnhx33ardgl640rckvwrys8grphvwsyt4ch2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUjQ2NmtLQ1JKVEgwRkdS
            MVZTUnNZWUsvUS9MVWpwb001bXd3L2lJSlhrCkJFajBHNzVobnRWNU5TV2swYnRO
            dEIyNnRpVVVTK01YWU5wZTRPbGN6Y1EKLS0tIGFwYno0aCtybXBLVFc1L2I5VFlB
            eGJtck1sVEVQMi9nZWgvS3hJTm9KWlUKCUUgCNrIGhAfvkFpfoSbyE8y37MS5Bww
            ET2BH5lqLdq35hGdU0jubOFrk4iLyC88x3YEyuIOjrHdf9eCLfQM/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-26T14:56:11Z"
    mac: ENC[AES256_GCM,data:NFCVIV6lxrCF9AzKvvu57k4cXM2QiBhEJb8Ie7Mv49qIJg8Mp60X9LYJp8fv5dv5PG+3Oj1WIu7YC4cS2VD+PTc7EYvhDUsi2FuSUUWjWt8KhYV/Tsp4tZcSVSlCu0moCnI9ONJhPhweINt8cBNVDwjuVb3uVgnRlhw6KMTCrks=,iv:IAeEJqz3aqAo+cMmyIiAyS9NmitZyFdfwCmp1AOYW5s=,tag:PFB9RbvrzJRCO3fE4qjiVw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
