# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: zigbee2mqtt-secret
    namespace: zigbee2mqtt
stringData:
    configuration.yaml: ENC[AES256_GCM,data:N8pqD2WKEmIMstXmm4/PFTYPbWIcmoN37kgMbMXLVEO5GwBwhMtuZ5RhaKJ7/P7/HmFUJf6MorpVGeZbJN4xCxcFO4u6bJPTjGhZqzsG0JFgbSS/8ecNkscpL0vQkQC7bmwQvPcJ/GvHlXM2wXYbVU+995dVm2T8f1hZiepAlB0zK5xBM0c0Uba+kKurGAfzN8mQbSGKafUgPABlNmWpkBFBIPlHAfyTSsoh,iv:nCqDbAFmYU4n8I8+ps4CPKrLsObRbiZcZepb8f3Ulu8=,tag:oLixI7H8hAvGuaPa3UO+OA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14j28wpn82nnskt0rzcaqxzwnhx33ardgl640rckvwrys8grphvwsyt4ch2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUjQ2NmtLQ1JKVEgwRkdS
            MVZTUnNZWUsvUS9MVWpwb001bXd3L2lJSlhrCkJFajBHNzVobnRWNU5TV2swYnRO
            dEIyNnRpVVVTK01YWU5wZTRPbGN6Y1EKLS0tIGFwYno0aCtybXBLVFc1L2I5VFlB
            eGJtck1sVEVQMi9nZWgvS3hJTm9KWlUKCUUgCNrIGhAfvkFpfoSbyE8y37MS5Bww
            ET2BH5lqLdq35hGdU0jubOFrk4iLyC88x3YEyuIOjrHdf9eCLfQM/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-08T04:30:55Z"
    mac: ENC[AES256_GCM,data:lRI+wbVvNGqp73eE1uf98Zmt8jB2eRGUQJo/QJo0rVFLyrKW09LloFsbudO6L9NLkyrS5cWlPN+oBdelkKUf/89SWdcHUO2IoN4PUljDy01GOXKPt5PxE1V9oZrk4ub0TTh2s0auYPPBWxwiW6W7GztbTiyZxKL2LbBkcytdtPE=,iv:G9sqj9d0azG2IUE9ApCHLh/WyMmtsfmuX/NtxbQyejY=,tag:koiSpsUIrEEfK9pdzB0S6A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
