# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: zigbee2mqtt-secret
    namespace: zigbee2mqtt
stringData:
    #ENC[AES256_GCM,data:WKtyGQ==,iv:mt0eDL1oAq2B7VW13JWoLO9Ek+CUVDdbc1r9zM6wGu0=,tag:RRLf2wGKYMfIp/k/H46P0g==,type:comment]
    ZIGBEE2MQTT_CONFIG_ADVANCED_EXT_PAN_ID: ENC[AES256_GCM,data:11DFf7Ksk84=,iv:oT2XWUbTkSQ9y8KolHreF1HlwRi9KOoJP8Pi0KoTn4c=,tag:xaT74lN+Ws7EK5YgTjQ9vg==,type:str]
    ZIGBEE2MQTT_CONFIG_ADVANCED_PAN_ID: ENC[AES256_GCM,data:bC80x5Wn0OU=,iv:LLpW0izNJb50aqjSPps7B8I9SbSIeKo/wHN6QRlBzZ8=,tag:rFVvIVriOh3DZ8AxngaMXg==,type:str]
    ZIGBEE2MQTT_CONFIG_ADVANCED_NETWORK_KEY: ENC[AES256_GCM,data:phbunr0p/Io=,iv:aw7RpS3bsKHchnJGQAIVFeDmLUaIx1EbfZYszDEibBs=,tag:JUzU8m/S677LZ4j6oKUW0Q==,type:str]
    #ENC[AES256_GCM,data:ZRSjH28l71AxfA==,iv:VSPNuz73Zv7kiG2fFaLeofMGdPdn0+ZzoYuvIqU1gCw=,tag:4XDX4irfaOSBWwPUCGOA9Q==,type:comment]
    ZIGBEE2MQTT_CONFIG_MQTT_USER: ENC[AES256_GCM,data:qL/Mbg==,iv:2DH0MMh0mhCNu2bK44ANB/3NTkwqJ0QS87xTzyjI5i4=,tag:qfdHkF5ajKTCdZrwN3eQzQ==,type:str]
    ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD: ENC[AES256_GCM,data:v8qSaNnjJeU6zIqCLUSRtQ==,iv:wrg5T28OS+6JxfHMTiUGdIERwyhxlvoybB7yz1gDT4o=,tag:jIHlizYMFW2PjkR0FgayuA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14j28wpn82nnskt0rzcaqxzwnhx33ardgl640rckvwrys8grphvwsyt4ch2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUjQ2NmtLQ1JKVEgwRkdS
            MVZTUnNZWUsvUS9MVWpwb001bXd3L2lJSlhrCkJFajBHNzVobnRWNU5TV2swYnRO
            dEIyNnRpVVVTK01YWU5wZTRPbGN6Y1EKLS0tIGFwYno0aCtybXBLVFc1L2I5VFlB
            eGJtck1sVEVQMi9nZWgvS3hJTm9KWlUKCUUgCNrIGhAfvkFpfoSbyE8y37MS5Bww
            ET2BH5lqLdq35hGdU0jubOFrk4iLyC88x3YEyuIOjrHdf9eCLfQM/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-08T00:53:31Z"
    mac: ENC[AES256_GCM,data:Dy60ns4iVgOwrS+dZoc/TawAPgLCxw+JWDgv1epEVjAuoeJIrP/LfhVC/OrOEbRDs8IO4n7FKz+bmyp7imMymJ5GKj9HiysJ6N+CCmXv3/lyDXBsdxlqX2PZPMKLzsPw3Nkf15ZkXXkMiidCbeNsnP7gbxxJCg8jhyuS1/9Tja4=,iv:MFZkQc5wrvVf54r5m9IT4zufL83AERs5gACntEG0r1g=,tag:9hH9ZAFQyjFnV7Tp0nZ8VA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
