# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: zigbee2mqtt-secret
    namespace: zigbee2mqtt
stringData:
    #ENC[AES256_GCM,data:WKtyGQ==,iv:mt0eDL1oAq2B7VW13JWoLO9Ek+CUVDdbc1r9zM6wGu0=,tag:RRLf2wGKYMfIp/k/H46P0g==,type:comment]
    ZIGBEE2MQTT_CONFIG_ADVANCED_EXT_PAN_ID:
        - ENC[AES256_GCM,data:T0eTMEP8pSjMpn6bEutlaA==,iv:TDU/xwRDy4O6b8hzeLpSJCNQR3vA/j3V5EolTUDi/So=,tag:RTgbpCvxlodidnwag6O8rg==,type:str]
    ZIGBEE2MQTT_CONFIG_ADVANCED_PAN_ID: ENC[AES256_GCM,data:BJrt+70=,iv:q0JNJeM9w5/MYGjND3ENl5jnWs8q4jUB/525xRM4L2M=,tag:gQoDuDecyFdDL9bTC63SnA==,type:str]
    ZIGBEE2MQTT_CONFIG_ADVANCED_NETWORK_KEY:
        - ENC[AES256_GCM,data:2LlF5uD8HEPx9c68spcGt0ge99PAQPWYUngXUEKv01E=,iv:wvSjZ4UuIxk6XYpjjNhHySkvppqklwgMItVr2LOAWsk=,tag:hGgMw1h4cGRZtEMjKjBkNw==,type:str]
    #ENC[AES256_GCM,data:ZRSjH28l71AxfA==,iv:VSPNuz73Zv7kiG2fFaLeofMGdPdn0+ZzoYuvIqU1gCw=,tag:4XDX4irfaOSBWwPUCGOA9Q==,type:comment]
    ZIGBEE2MQTT_CONFIG_MQTT_USER: ENC[AES256_GCM,data:qL/Mbg==,iv:2DH0MMh0mhCNu2bK44ANB/3NTkwqJ0QS87xTzyjI5i4=,tag:qfdHkF5ajKTCdZrwN3eQzQ==,type:str]
    ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD: ENC[AES256_GCM,data:v8qSaNnjJeU6zIqCLUSRtQ==,iv:wrg5T28OS+6JxfHMTiUGdIERwyhxlvoybB7yz1gDT4o=,tag:jIHlizYMFW2PjkR0FgayuA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14j28wpn82nnskt0rzcaqxzwnhx33ardgl640rckvwrys8grphvwsyt4ch2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUjQ2NmtLQ1JKVEgwRkdS
            MVZTUnNZWUsvUS9MVWpwb001bXd3L2lJSlhrCkJFajBHNzVobnRWNU5TV2swYnRO
            dEIyNnRpVVVTK01YWU5wZTRPbGN6Y1EKLS0tIGFwYno0aCtybXBLVFc1L2I5VFlB
            eGJtck1sVEVQMi9nZWgvS3hJTm9KWlUKCUUgCNrIGhAfvkFpfoSbyE8y37MS5Bww
            ET2BH5lqLdq35hGdU0jubOFrk4iLyC88x3YEyuIOjrHdf9eCLfQM/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-08T04:15:12Z"
    mac: ENC[AES256_GCM,data:aqSM4scwrlOugKEE7gG3fIeEtTKp75vDoBOLHkE868okFBrv/IDS/KptBeANlvLjFIXTg4k5j3HdO9wXrTm5zzieOSk3KUSKMZyA/W7o147XfUiaf3LrfGJGahYpc44tSEAcc4XghdvyfQanrLnn2e/VMsP7k8RcdwbBVs6PKHc=,iv:cyl2GGJdyY1h31U8FD4tCiRacnTA+mxeFQdAEfQvEP8=,tag:GVB3eLc2rsjWCrBusAQx/g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
