# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: zigbee2mqtt-secret
    namespace: zigbee2mqtt
stringData:
    configuration.yaml: ENC[AES256_GCM,data:X2Odv0p8+ZT5ELmeijsrsDcACGgwr2hbR3pL5rILgriwjmJhJSjatGOUOBBJgH1MnjChEzPa31gk5InplKd1Vfu5AKM73sqsfLe1ulRGcvke2mQdgOuQ4s51bQiSh6a6s4q4h5e8V6r9XJMn6L4R/bneBkC0w9eo1wXXSBs5wBNYHID1xXIfmyzV86n5ThN44/bmz0Ine6kdGkzqnV25/HepBz0ELPQ3ALxMwPDFNrvaDybNXAc3LpT1Qq8MtLkQcecPtlhctR2NqLKRUK7culJLEoXBT80CPcsMrXNPxOXaf2PeIkw+NI3c6lLpVLJ4O3o5rENbNczMQmHMeAaiRL3majNKNYA5GLjmXNC0JAwS8TGxwnqIXIoFLolC45nDbgg+EEnXYmmTXujiEwgwA+6aVWtYgr7Q84Qycrfb2tbPeuYCuaBWqk5zRNTYvMpo6FCg7dqyDJl8T0w1qUeaTp9edILDy8k9QFfm1fzVORnyvpNLMxZVPmZd/E9pYLh6G9IcLSm5uNG4HyUwv2vaBiP01GOCaYHvCM2mfrpkD/q5Zz3zvxVmLIiLS9cjlT4+ZLieIbiiV29y1iLeqnwhAP6CeKA+elwNJU5WGimLtaC9g3UKchiLMvu0JbVD/AXbpkMjJPDO8l4x1qOMPLc3mXI4rMkQPUk84UbmCZoFbvnSrcw+mGiTtYcacSrvkB5InjaejF0shnZIJtLwds7RMwG6IQ+oO53EUGPrp4BkSs9rnM4ViWB9kGi8ERmKifB6BIjGjM3dm9XB3GYlS/vvo87FX9qrtHH8KMtjWfwt8XudLzmbd8UheinHPwsjHJcV/uyMLKJ44fAApgUaq9C5tOmn63TV6C4m6WarA+V3iiISS1nl4Y1mnHY4J0x5Tfce+TLs5v0D4wXAyO8puHIw10ifPADkj7xZ+wT+PvOr5rDY5mr5MtxYqgKd2slHhLIxFJGyF1IHagRoV60vZ3aEH9sBCRrQDBFhljeRAGHwZTpELgOC5c7NaUXSdSUF7QEQ48p1XkytHd5xJUKtGKYjRGXiOuDkr9dLeUl2vXV/+KrDuEKATu6Hl7LYFQrhYqbj6Bzzdw2ay6yT1mMjo6/M0+UeeZZv+M38M7geyryrm4qhP6QBow3u32Hv7yeTW4+mylbYr9knUFzrFwn5DxUjakyawhTYszIXau2l8mIuHQynY9H19KOXB6hb38zcVrEEFlhFh7fN2qPAD/IXRWpjTcW0ZsH44WUw0kGv+q+adhg688QtutdFnXoFrOsKYNfh3jZ27SGKluCtai5O03uSoKcF8YCzE7lhjPfwYfvghlnUeQ6rYV7NvjGunj6RNbgm+mozrMnqtxl/o4VQdTbnN+zgOmNdS8Zn2/WRVeEasjXiOcYQmd0eb183SaWtyTHheYyUgY243nVq2CKFvemL5C9L0ZaGDPaq4xxO0Hq9y1jBvQ8yRD35CGaThTwqnQ==,iv:mao9iOmPHmKZHu5Hor2FGCbEyBHlFJIwQOms4laRBPE=,tag:1+6eqk7u6Q/ZBkh7t0k/3Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14j28wpn82nnskt0rzcaqxzwnhx33ardgl640rckvwrys8grphvwsyt4ch2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUjQ2NmtLQ1JKVEgwRkdS
            MVZTUnNZWUsvUS9MVWpwb001bXd3L2lJSlhrCkJFajBHNzVobnRWNU5TV2swYnRO
            dEIyNnRpVVVTK01YWU5wZTRPbGN6Y1EKLS0tIGFwYno0aCtybXBLVFc1L2I5VFlB
            eGJtck1sVEVQMi9nZWgvS3hJTm9KWlUKCUUgCNrIGhAfvkFpfoSbyE8y37MS5Bww
            ET2BH5lqLdq35hGdU0jubOFrk4iLyC88x3YEyuIOjrHdf9eCLfQM/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-08T06:16:56Z"
    mac: ENC[AES256_GCM,data:+VeHrGarr39/E6Y2TCkQeS8lBJ8hx4DGVcqex/TozUpNv5IjN5dySzl736I7aICryVwKyzOPWL+rZK0HGH1c+1wKnZEn04GfUS3PKf48ZDNbyisKWlIbEjRbXk8ZdJOBX4t1LseuomMPu3NY2tI14Q+uXrds0ouK2KRpNaq0sY8=,iv:M42rs80zrJWaylWIV3aHGBsjoBj63zfJglLb8uXUT1U=,tag:tUucszrHCfq/Yhfr2C4T9g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
