# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: zigbee2mqtt-secret
    namespace: zigbee2mqtt
stringData:
    configuration.yaml: ENC[AES256_GCM,data:irJvBk1Zf59zB476ql6Aclyy+YMa9UfaaEk26Tb8BNTV8umA/y2/1njOkM8FouS4pl9UZUnVuQwo4HdegdPE1ddSJmQKcLvSQGffJ2gGYavtZ5jFZTQlLmLdlRtKx/4PUzpoLigpVlJDX2VPoBC4k/ajNUVEbEAt/R6Y1zAFJev7EQsiMFRQLGJT5ANVUCrUXYIeTrnUvzFO4/PO5keumzugXqNvSlyHfgKajjYrRmHSRSsiJSj7SY1mIAt479V6IePQjpkiJqsSp82GjhboxkUL9TwE7NFY4vMA8ChmTSqV/VpH0D2y4nO2+LaNKoUJ53yQGIVSdixcgXLv8hhJFoLL+Gi1Oi2JkyzJ0y4CokfDH83F8c5KKDfVniIyclrdoUlu7NumfAIX/XRyulbMnN4TWo5jdFa8ijzId14JmwsZVIr6fgwxI0eC07WV97OGLoVXxSkurUL+1X7NoqA9szFvFO/q3QYS09mEAgrr2mTmeveVa1bffbdAtQb5bPhEkovyamfFpwWXHhk7fWJ8OfKBCs+XJECrCcJ5eI/o7TyIUe0ukHgX1yhQNQLoI0BKrQy7vQf+tb0ZjwhRHMJG65iO3/wVoJ3Ic2hGe1M25FjJ8ggElFcgXAd1Klw0B1LM1lNPFBxc1FWB99vc80XMGUw8QUu5N+nhFlWXaTurZC+7l1OtrqG/0GH1H7Y1kngUAnxgxfCt2aLG+yZxLObNtlzJA8HuU8sKcDLHq6nObKDE6VWyH3TzH5QmnaZCVe/YZi/dPF6OBtiWul3QFWYy7RX0O7t0mbzW8E7tWv0hDH/uZsi+ALBn8DBgpi9eBO3r0lAZwPPyDXJjWuePaeqLAbu0T07yIvSsKFz5NYC9TMVGO6kjURTqf4fdmD8H7u8v8l6vrSsIIuA4mxs+j28C4z4z8jHlqD13jzF6DqnTHEgWtT0h36q1eOXwfhhe5aEsac2iaqoZlX+7r5Sv+g9yDqAM0Qeww1ecKYKPbujOWZfUc+RnBXnh8pUPNAi+wZG4uGQt6kIOEkGRWgycNX7VqLb2SzK6C2K8l59dJiYWJgUOu1a3972NbS3otdohzqYBRdNthP9B3/aFzTTNXCKj8+znC1Bl5Ole9a0FxrrYvwCFGb4sGkTCr4S+cIQ8oE6D3pDuwg15IuzmJyW+jSRdRFpsUhg/TsI22Z9+5I3367tabxL7,iv:eaNm4YLs+AqgQnVwn2kVrxh8e4yVUjheE2FgNWJk5DI=,tag:yc4es/19Gez8FUWC0d90RQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14j28wpn82nnskt0rzcaqxzwnhx33ardgl640rckvwrys8grphvwsyt4ch2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUjQ2NmtLQ1JKVEgwRkdS
            MVZTUnNZWUsvUS9MVWpwb001bXd3L2lJSlhrCkJFajBHNzVobnRWNU5TV2swYnRO
            dEIyNnRpVVVTK01YWU5wZTRPbGN6Y1EKLS0tIGFwYno0aCtybXBLVFc1L2I5VFlB
            eGJtck1sVEVQMi9nZWgvS3hJTm9KWlUKCUUgCNrIGhAfvkFpfoSbyE8y37MS5Bww
            ET2BH5lqLdq35hGdU0jubOFrk4iLyC88x3YEyuIOjrHdf9eCLfQM/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-08T06:02:43Z"
    mac: ENC[AES256_GCM,data:gSn2h0fYn3vtaqPz6rSZANBUFyh6gt8MIvUKor2az6RZ4SbzRBhqwD1hl0g0HP4B67noBC6Ee/szrUBzr6Y4nWVRw01No7H9KB9OeGYl3z9uazPCkeHsd3VaZrXEr6GSYxDXyA9+eqWOT/eyqfGVa0fczzYMrt7uX9BhJZMA8QY=,iv:TinLlIWClHdnXT9PDBrvF6ex+8rDgEwNAoOqCJZs4Bg=,tag:Ba+5kVaq6KIX+p2AZBnVAw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
