# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: zigbee2mqtt-secret
    namespace: zigbee2mqtt
stringData:
    configuration.yaml: ENC[AES256_GCM,data:1FQsVilRhr9plPSKmf7VrUlwqha1UYB4Dbqs9xxU5THGcNzuiMahZkT0RZft+jPnS9XZc+r5LE//n34o7vQJ8ssiqYsr+iAKYINXzB2KNltIAYi5eR4qUdZD0XwVmCBgZgWolfPLqdSZzqtZjt+2scsRIwRT7pI2QohNYvCoZ1Vpd2GZImSORQkfuMqqfzhmNpvrNUfzKRQaezBeQxGkCP0/Lm7wV5+D3G/60mO5/4aUG2c7/P47+HgaUMt+NJWvNKtzZWqdDEj/Uib3X2TjQNkeZP0uP93jkhjWkj0mxs9cVwvOfGalyQM4uEU4XswhShx7AisYcVo0For4DLbo/tt/Je63EtcpyUvLdqwCBX/jDX99aLiLR2wXJ6aZav9sEEhssKCxfOXNohrcYNDnXVTQelVtNmc+wCAs8UPc6vgNZIhSugvUk8RsaHdWayc4/xXXPftME0laxc0ZwnyUtELdfnSppI8rxRwbWqmM+HdYnbSqNvvFI+sYU5wX/uE8DlRkkUbd7ANXAmVAkZwaTMWtaxiOfiRIF5OdJpr42WGWzUo8T/ukxHYU6F0vWY0KqrY9KNW/dolbiPtJCqNKtz/Sgnr05Y8yxEvIHAnUIXC7i+oo28xc+RoGmnkYMpeJN/3IOhUGG37PKf3UuPBgk3Rghr4Qm+1b2ddeniBTGY2LOR4wpnOMX4gEpHIt0Du/O5GbNt2H9QQdx7OvmJfpq/a+aUOlSJU/aFUCJTvpvwpV92fTC5TYSi1F8JRZB8y1F5Dk7gxQDC0F89+CYwo2kTHZaGnUq0XM7BuU+O0TK1Sywe6pBvhXTgAgoIEtzg9IfvUOB6A8rV0QZJ+7zs9NMke7aHYtchAtkfrlwOgxmiYQEp5r9w+lkvf3KRrhVrzvWhzESXlzbDKFFmILFu/mCNU3Z3h3UDqge87AIes3YJPIrsWY2MSj03glOzD2bgJSemLRjzRs4R//RF56KV98qI/K0xF93jH2x4/YmpDl/WmgzBhEigXCPkQpnY+/XRVeYYWFO9BfTo6cTJHLN6HoutviIMPLPJAiE8X7XSH+kQm1I/N2eELtyYrjdeSNp1psPFViArIp8adQ/eDzUyzHrqR8KRJ4T91aFPGtFT2VdJ3VNALtqzT8pw57fWBfw2o4Gm25mhZInAot7FsaCswUVyLcr7ZI14wUaH7Gv5uKPTb93ifCE9IGzE+NHDVe5yJY83Fu9+xUheCsGD+AT31azXekfbyBwg8t700O2wA=,iv:v/UvU4z7JyAVF0BzA7yhwq50WElZ7N7X7T8PlsEsaQE=,tag:LwBc5cQ5pCvpsAWsD7vGEA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14j28wpn82nnskt0rzcaqxzwnhx33ardgl640rckvwrys8grphvwsyt4ch2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUjQ2NmtLQ1JKVEgwRkdS
            MVZTUnNZWUsvUS9MVWpwb001bXd3L2lJSlhrCkJFajBHNzVobnRWNU5TV2swYnRO
            dEIyNnRpVVVTK01YWU5wZTRPbGN6Y1EKLS0tIGFwYno0aCtybXBLVFc1L2I5VFlB
            eGJtck1sVEVQMi9nZWgvS3hJTm9KWlUKCUUgCNrIGhAfvkFpfoSbyE8y37MS5Bww
            ET2BH5lqLdq35hGdU0jubOFrk4iLyC88x3YEyuIOjrHdf9eCLfQM/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-08T04:37:40Z"
    mac: ENC[AES256_GCM,data:K6Uw7GL9N7i+F8sPv1nrSBjlPYXgyf0MjyD3Rh74Z0u5EBKf6hFTJ60sITZnfuyCuD7A8h7o5zk1ZBHz6kIrpvFUvqVP0MxgjCSf8usaM2HcsKFiyZO5MeuQJ45/QzYttrOXaeLSHWnjLLMFHQE7a9bLrcYhfDy6saNB+G5XKgU=,iv:WFqw554+qgqudgeR9zOaUWcj1Ny8sFviaY1HpaiaaQw=,tag:0/2DekfBcb8TR7E4IEvOoQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
