# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: zigbee2mqtt-secret
    namespace: zigbee2mqtt
stringData:
    #ENC[AES256_GCM,data:WKtyGQ==,iv:mt0eDL1oAq2B7VW13JWoLO9Ek+CUVDdbc1r9zM6wGu0=,tag:RRLf2wGKYMfIp/k/H46P0g==,type:comment]
    ZIGBEE2MQTT_CONFIG_ADVANCED_EXT_PAN_ID:
        - ENC[AES256_GCM,data:N8VkQwQTEVY2YOdFJxY5Tw==,iv:vD4ntTBXeDRi7Se2zVOQ4zEnQYjWaavWa8OsNErl1EE=,tag:tiuHKOjuPBszCVTfPobjOQ==,type:str]
    ZIGBEE2MQTT_CONFIG_ADVANCED_PAN_ID: ENC[AES256_GCM,data:Ds/lcIU=,iv:pG0heqgBp1ZUMSvZrdVzyEAJTdYm4lNcLHI8drVaOoo=,tag:3JJz8+L9fxqV1WWwIbBDrw==,type:int]
    ZIGBEE2MQTT_CONFIG_ADVANCED_NETWORK_KEY: ENC[AES256_GCM,data:1wplclsh/k/N8OBj9/q1zUEvwB9wiS0250v3f4D6iA8=,iv:hKGuuCyj9/j0Ym7FtlyQLoV3vlA9HrVM0x5Zn7vLSeM=,tag:rT/1Rquo5NMSGMeGsIpJ0Q==,type:str]
    #ENC[AES256_GCM,data:ZRSjH28l71AxfA==,iv:VSPNuz73Zv7kiG2fFaLeofMGdPdn0+ZzoYuvIqU1gCw=,tag:4XDX4irfaOSBWwPUCGOA9Q==,type:comment]
    ZIGBEE2MQTT_CONFIG_MQTT_USER: ENC[AES256_GCM,data:qL/Mbg==,iv:2DH0MMh0mhCNu2bK44ANB/3NTkwqJ0QS87xTzyjI5i4=,tag:qfdHkF5ajKTCdZrwN3eQzQ==,type:str]
    ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD: ENC[AES256_GCM,data:v8qSaNnjJeU6zIqCLUSRtQ==,iv:wrg5T28OS+6JxfHMTiUGdIERwyhxlvoybB7yz1gDT4o=,tag:jIHlizYMFW2PjkR0FgayuA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14j28wpn82nnskt0rzcaqxzwnhx33ardgl640rckvwrys8grphvwsyt4ch2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUjQ2NmtLQ1JKVEgwRkdS
            MVZTUnNZWUsvUS9MVWpwb001bXd3L2lJSlhrCkJFajBHNzVobnRWNU5TV2swYnRO
            dEIyNnRpVVVTK01YWU5wZTRPbGN6Y1EKLS0tIGFwYno0aCtybXBLVFc1L2I5VFlB
            eGJtck1sVEVQMi9nZWgvS3hJTm9KWlUKCUUgCNrIGhAfvkFpfoSbyE8y37MS5Bww
            ET2BH5lqLdq35hGdU0jubOFrk4iLyC88x3YEyuIOjrHdf9eCLfQM/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-08T03:56:08Z"
    mac: ENC[AES256_GCM,data:JoCLpY6Up4kBRdRz/waMkaoVlxt8LFd5vsDq7rBmRPNgw0Eq/+Y0PRANYM61MKi8ePwByoOVXC+WpApc1eqgXXBCpPPEBbDsbE0fm9ASu676NbUyUvMWen6YaxEpi0hDHt/ZKMeR448ol6fX4sUgpu4XMOm1hrePk3fRK9T7e+0=,iv:tc7K+dnpUSlYJRbSZ2MO79P4IfhchNutSiF1S5K5X7Q=,tag:4mn1JMZRfg1lW87crM8/2w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
