# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: zigbee2mqtt-secret
    namespace: zigbee2mqtt
stringData:
    #ENC[AES256_GCM,data:Zic6bA==,iv:R0jvj0mn2/cPrPzJjjXw/Q35Iq0PcXvgVVYWazOY51A=,tag:owl/hKdOC64sBcg9+Xb7Xg==,type:comment]
    ZIGBEE2MQTT_CONFIG_ADVANCED_EXT_PAN_ID: ENC[AES256_GCM,data:wcnMQvoktlQBjPpcSEbnRQubgTp1wPM=,iv:kUtrSo+PTN47Bn9EAu8TxzfBMW2U/siYYamFgH+M5d4=,tag:rb57lE1tI6xB6GxXlKlBgQ==,type:str]
    ZIGBEE2MQTT_CONFIG_ADVANCED_PAN_ID: ENC[AES256_GCM,data:Uc++BnQgS7BDzhrki8FZfbt/OQ==,iv:y6dYMddVaGuqfYCtID8h4Yzt7fgfJljgUMh+bZEA0cE=,tag:8AX210lXHyrqR/dDIBDjBw==,type:str]
    ZIGBEE2MQTT_CONFIG_ADVANCED_NETWORK_KEY: ENC[AES256_GCM,data:otTBtOjRMFFitHxhkoZtcBjSnXIkTjQv,iv:/ZQSixkT2JWZgCNn+PfLyBUHCyy4DCP8lzkJ+kl0C8M=,tag:TELsv8Ggdko6Em9olwWBFA==,type:str]
    #ENC[AES256_GCM,data:QANgkH16+JaNAw==,iv:RNzBajwP9allEhmX76S1dC0fFoa/ZMnJibvgnOiyOkU=,tag:ZRhTIF0OxqrEgiaPWlBvug==,type:comment]
    ZIGBEE2MQTT_CONFIG_MQTT_USER: ENC[AES256_GCM,data:4+R8MQ==,iv:yqmcqVgjvqNih+sQz6iv5OGNM6ioWQNPj09Quyx+W2U=,tag:qCSyHEOFr3oRIEG4kRNPAA==,type:str]
    ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD: ENC[AES256_GCM,data:Vl0kuMgX9cbXSpKTFKjQRg==,iv:oXN2t/dWUGIuYgAWHQk0zZ9wljVeZyjbhUUheXNI1ac=,tag:CxoUMLMc7eHadOMvlNWdng==,type:str]
    secret.yaml: ENC[AES256_GCM,data:r16adUnSjYoKC623DPFJFuWE0AbyRrT2+fAR0flGQ4RiYgfHGCGacPv/jEZeCb4LhPytt6iNymto36FdY7beFsFeqrKln71yzZ7+KAli2EiRxneBxQT1cT9lAF8UVpDm04RNYB7vMvUo1h3bO/WwNjf6sZEIFTgjKEv44EZz85URfjSdtMUaStv3LvWJkvHZz1A3TupR075wm41VWwezBd4TFSLQF6dHhFrmePRcn/jvri2oIS+HoMHNXnKDocXE+hmsZ5bO5hK9Ta2hZGM7Pu0AXLP0jw==,iv:NL3ZjwqsezJgO7R8f3fCiKCCI3IoWEBU/9AQ+e3lXV4=,tag:+wXfqKMX9Jv7vM4Qo7h2Fg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14j28wpn82nnskt0rzcaqxzwnhx33ardgl640rckvwrys8grphvwsyt4ch2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUjQ2NmtLQ1JKVEgwRkdS
            MVZTUnNZWUsvUS9MVWpwb001bXd3L2lJSlhrCkJFajBHNzVobnRWNU5TV2swYnRO
            dEIyNnRpVVVTK01YWU5wZTRPbGN6Y1EKLS0tIGFwYno0aCtybXBLVFc1L2I5VFlB
            eGJtck1sVEVQMi9nZWgvS3hJTm9KWlUKCUUgCNrIGhAfvkFpfoSbyE8y37MS5Bww
            ET2BH5lqLdq35hGdU0jubOFrk4iLyC88x3YEyuIOjrHdf9eCLfQM/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-08T06:37:47Z"
    mac: ENC[AES256_GCM,data:bY8zORCtBfEQ0I9UAkInQPd5EhL2TxwWLTtbDY98i5jKTKnAdpuyDgqpXhcM5Slg73DZ8PCfU6eIimbPOxrO9YWaHF2kIoem5VSR062FW7VpCdySXOCBY1ufbL72B7zCOf6L8aQCSTpDRm0tVRaHxU0XV0rorZX9sj0CE483KLA=,iv:kpptTw/WWVCvceMx4uAgwHMdMWrYKUmnzlIYPe6paIo=,tag:q6lvmxhqHpqkBw/QehU1GQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
