# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: zigbee2mqtt-secret
    namespace: zigbee2mqtt
stringData:
    #ENC[AES256_GCM,data:Zic6bA==,iv:R0jvj0mn2/cPrPzJjjXw/Q35Iq0PcXvgVVYWazOY51A=,tag:owl/hKdOC64sBcg9+Xb7Xg==,type:comment]
    ZIGBEE2MQTT_CONFIG_ADVANCED_EXT_PAN_ID:
        - ENC[AES256_GCM,data:s3RG,iv:gcFqz4D5TrJxMbbf1myLFsSoeHnOzM6vEgfzBGUtLpY=,tag:692QIq655UBa8oIbrOfLSQ==,type:int]
        - ENC[AES256_GCM,data:TQ==,iv:4JX/4AvVKFdmNtefwwNQeSv6lfeCGZ3uJEXtjhRFkUg=,tag:us8cwQYOo5jWHS+9xJIdwg==,type:int]
        - ENC[AES256_GCM,data:l5oH,iv:0TefMR5CJG0CHrhqANDjGrq0ch35Xa6M3oISFjzuOMc=,tag:Bg2YeW2UdsatwPCZV6RW1g==,type:int]
        - ENC[AES256_GCM,data:rg==,iv:yoNty5dcv3h9nyGihYgu5Mf5nXI0MAPQtkGO6yCdokQ=,tag:vO7fca4Myyi5aqS6AmvK+w==,type:int]
        - ENC[AES256_GCM,data:oA==,iv:zS30AlBzOlOvt2TOgupesmO8sgEN7Y55aSQGHy0DMTM=,tag:HmgGrUZJPKFPmdreDRoLKQ==,type:int]
        - ENC[AES256_GCM,data:IHY=,iv:cr1HvKvGhnwCMTDi9bssGcIxGAY5bSS741szGlH2iWk=,tag:JgppSAEh0LfjGF8h/NS7sA==,type:int]
        - ENC[AES256_GCM,data:zhKM,iv:fOU3rwhHWlGv+Q5ElPO51cAN+8zKbYJu+o8PGM1bti0=,tag:eJv6Ck3nZ1utnlWcrvCnkA==,type:int]
        - ENC[AES256_GCM,data:VSc=,iv:8RPhcchX9MT9WqI5Wr6mJHg4v71t6SxLsNkuFNsjRDc=,tag:aAOG6lKX0hMlX1cBAdsqeQ==,type:int]
    ZIGBEE2MQTT_CONFIG_ADVANCED_PAN_ID: ENC[AES256_GCM,data:X45wqn8=,iv:rkXNGQ7YABNQPmehqBMpA6kMpldRICYuHSxhskEt5gw=,tag:jv+pEw7m+TKSjt9aJ4Nycw==,type:int]
    ZIGBEE2MQTT_CONFIG_ADVANCED_NETWORK_KEY:
        - ENC[AES256_GCM,data:dXok,iv:namhDkZD+wfksvxhb/pjkPuX0qdQHn6gMFlB0ck8MLU=,tag:KOpkhPCUm1kMwAfp7GnP3Q==,type:int]
        - ENC[AES256_GCM,data:2s4t,iv:+h3w8V8DAKHQUEroi/Aj5Eu1cg5ue9yOagRIb3GJpC0=,tag:Wvq/1eHngUkJjrjmLQ3sog==,type:int]
        - ENC[AES256_GCM,data:alo=,iv:3JQr4BQkiN1cFyEtPugwD0ka6QZ2XH4nChcVlTds7kM=,tag:T3m+YtOG7iZDvf/ELW2ryg==,type:int]
        - ENC[AES256_GCM,data:uXQ=,iv:tvduW2THZrlZT1n4s20sS1AEIxhFQLT4pM4QkmMgEa0=,tag:Lm4QEHfguD6iGnlDlaB0uw==,type:int]
        - ENC[AES256_GCM,data:xVv3,iv:vcA8Or2WCAnoj/9A9PGYIp3XnHbb8jpFKIrZmlbYIW4=,tag:u7nqfePeKIgCD6FxyHID+A==,type:int]
        - ENC[AES256_GCM,data:5E4=,iv:dgJGB7iT2CZMGOwlITVF7II/GDIixKU6QuwcNmzXXpI=,tag:oMbEoGJpL4s9nc7NbTf4TQ==,type:int]
        - ENC[AES256_GCM,data:mT4v,iv:JIFpo8tDthC0ABtke+6aw8MkF0p2a/GTJj/gexo+/Ck=,tag:UO/VBYLkc5FqFR2rcsPrxw==,type:int]
        - ENC[AES256_GCM,data:/dI=,iv:d17c4WHwYFEcWizrO+XjZMg73F/5CafTI5kD9ev9wN8=,tag:KtppOptVWElS3OMEsU96lg==,type:int]
        - ENC[AES256_GCM,data:1ik=,iv:Y4VM6+3nvjdqfvYpgNHrbUHQuQ7SOnrxUxYQbPnwFxo=,tag:e/JkhkoxJ8V7+CS2GtxxFA==,type:int]
        - ENC[AES256_GCM,data:lKk=,iv:eHbWV1aLlL5Yj4uV3dkmNGv5jjF70wlrwnCCbmx/vfk=,tag:CwPl6vovq7B/DLA4TjHuCQ==,type:int]
        - ENC[AES256_GCM,data:NHA=,iv:mtGckc1N+G9DmOMFRZO0tEol64GtpkwfKqRyPEMClxI=,tag:Y++T3xW3CXecEoELchR13A==,type:int]
        - ENC[AES256_GCM,data:WF4=,iv:IH35v5qc9AIYAA0uQ5vvcjTCJGSk3wxVZki6zsqASjo=,tag:al3zeiQq1El7rWoluVVAgw==,type:int]
        - ENC[AES256_GCM,data:ghk=,iv:GlcYBNNiPKJ0zL4NzxXZvNmpaRuaPM1w+MA2mXLOFds=,tag:iZcxLQmm3OVrRbPOtONJCg==,type:int]
        - ENC[AES256_GCM,data:J4W2,iv:A14fCARZCRIBMUl2PBNoibLbNAZTQgLahT7iUliXtxo=,tag:eKsU0nWSNwXhpolYuArYLw==,type:int]
        - ENC[AES256_GCM,data:9O2y,iv:yhomAlvGMz87ZAFZEbNy/LitLDJum+7jC5EWESDJdb4=,tag:O296vryMweUspOiv2bsWfw==,type:int]
        - ENC[AES256_GCM,data:OfFA,iv:VnZkaJWfqAm+1XH9d7/HHA36xgf2mUfMQTmYjruwhbY=,tag:3m07aWMzZdVnmef++zVFJg==,type:int]
    #ENC[AES256_GCM,data:QANgkH16+JaNAw==,iv:RNzBajwP9allEhmX76S1dC0fFoa/ZMnJibvgnOiyOkU=,tag:ZRhTIF0OxqrEgiaPWlBvug==,type:comment]
    ZIGBEE2MQTT_CONFIG_MQTT_USER: ENC[AES256_GCM,data:4+R8MQ==,iv:yqmcqVgjvqNih+sQz6iv5OGNM6ioWQNPj09Quyx+W2U=,tag:qCSyHEOFr3oRIEG4kRNPAA==,type:str]
    ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD: ENC[AES256_GCM,data:Vl0kuMgX9cbXSpKTFKjQRg==,iv:oXN2t/dWUGIuYgAWHQk0zZ9wljVeZyjbhUUheXNI1ac=,tag:CxoUMLMc7eHadOMvlNWdng==,type:str]
    secret.yaml: ENC[AES256_GCM,data:r16adUnSjYoKC623DPFJFuWE0AbyRrT2+fAR0flGQ4RiYgfHGCGacPv/jEZeCb4LhPytt6iNymto36FdY7beFsFeqrKln71yzZ7+KAli2EiRxneBxQT1cT9lAF8UVpDm04RNYB7vMvUo1h3bO/WwNjf6sZEIFTgjKEv44EZz85URfjSdtMUaStv3LvWJkvHZz1A3TupR075wm41VWwezBd4TFSLQF6dHhFrmePRcn/jvri2oIS+HoMHNXnKDocXE+hmsZ5bO5hK9Ta2hZGM7Pu0AXLP0jw==,iv:NL3ZjwqsezJgO7R8f3fCiKCCI3IoWEBU/9AQ+e3lXV4=,tag:+wXfqKMX9Jv7vM4Qo7h2Fg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14j28wpn82nnskt0rzcaqxzwnhx33ardgl640rckvwrys8grphvwsyt4ch2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUjQ2NmtLQ1JKVEgwRkdS
            MVZTUnNZWUsvUS9MVWpwb001bXd3L2lJSlhrCkJFajBHNzVobnRWNU5TV2swYnRO
            dEIyNnRpVVVTK01YWU5wZTRPbGN6Y1EKLS0tIGFwYno0aCtybXBLVFc1L2I5VFlB
            eGJtck1sVEVQMi9nZWgvS3hJTm9KWlUKCUUgCNrIGhAfvkFpfoSbyE8y37MS5Bww
            ET2BH5lqLdq35hGdU0jubOFrk4iLyC88x3YEyuIOjrHdf9eCLfQM/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-08T06:44:06Z"
    mac: ENC[AES256_GCM,data:9g0Q3KeaSywFBG1Hihes2iEOnvQJK1nho7vi23XtImQJQ/MoMRbXd9vemmJoWEikkYfawLC1fWhC42hJvlDGogLkyeWLk9WFY5ZfIyf9nD0pVxF1pkbgSL+lb5p/YtCqH68ohJ5jX3pHEeoZVp1KEc9kLa+yx1lAOVH7wlcjJc4=,iv:HfdRZR2VegtbIEfUALoywzgL2SPTBsJDrRjY61FWczU=,tag:m3Q8UOu/84FYO8OqQQxYHg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
