---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: server-db
  namespace: windmill
spec:
  interval: 15m
  chart:
    spec:
      chart: postgresql
      version: 12.10.0
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 15m
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      postgresql:
        auth:
          database: windmill_server
          existingSecret: app-secrets
    primary:
      persistence:
        enabled: true
        storageClass: home-cluster-nfs-1
        size: 20Gi
      podSecurityContext:
        fsGroup: 65534
      containerSecurityContext:
        runAsUser: 65534
        runAsGroup: 0
