apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:99BPqscLRppVYgi+ZduIgnRXlgwZPemu,iv:+8Ozu0sEO+4SZS0puh9aIM/V8wFOcgki1TIT37ou4+M=,tag:2RrMDJH2VPrA4d0kQVfR0A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14j28wpn82nnskt0rzcaqxzwnhx33ardgl640rckvwrys8grphvwsyt4ch2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKdnNnTi82WDFMZ2VsMXNL
            Q21NMTZ0WFdYK0FQUmVscUNiSDNmdTFDR2c4CkxqSlF4dDRJTnlrL0VzQjQyRCtu
            QmhBTlBvSTYvaHprNFk5ZkNMR3lXdWcKLS0tIGZVS2ZlRjlISGlmZDVoVCtRYzlw
            K0pFOEpjamQ1eWdjSTFuRmV5VVpQdXcKq1/x4XcOr3kPI3ZKM0t6PyJx1s/UfpXE
            52urbTgVnvALyxnWiI2cFZt5bolIrKdm/GZveMKy883Z4fmFO8wtgQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-23T23:53:53Z"
    mac: ENC[AES256_GCM,data:w7lKKb1wgnZvwSv3RwCJhV2qdZAk2Apc1cLH92oAmGabZt0HfglLDI4mJg0KlnxeAbmm/74X2Cf7eCH855XAoXl9cSXfnOmJWWpuEJBZIS7bcWlqEB5Ixoss/Iu6WSmhMMH8CrTW3Bkm3FokZ7Lpwc4ZwXk6JPDHXlwpSAaWpIs=,iv:N6Jx2548dAMN29aDyAeU0dM0AqrbIMXfAsu8whmbSw0=,tag:cJMIYdOUJIlwbxBcLbFTHw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
