---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: comabase-backend
  namespace: comabase
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      strategy: RollingUpdate
    image:
      repository: aitbase/comabase-server
      tag: v1.3.7
    service:
      main:
        ports:
          http:
            port: &port 8888
    probes:
      liveness: &probes
        enabled: true
        custom: true
        spec:
          httpGet:
            path: /health
            port: *port
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
      readiness: *probes
      startup:
        enabled: false
    ingress:
      main:
        enabled: false
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      # limits:
      #   memory: 500Mi
    persistence:
      config:
        enabled: true
        type: "configMap"
        name: "backend-config"
        mountPath: "/app/config.yaml"
        subPath: "config.yaml"
      uploads:
        enabled: true
        mountPath: /app/uploads
        storageClass: home-cluster-nfs-1
        accessMode: ReadWriteOnce
        size: 1Gi
