# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: app-secrets
    namespace: home-assistant
stringData:
    password: ENC[AES256_GCM,data:twqa7cw0gdHelLudQ8w=,iv:IfmWSpXPLpaeF91KhWOnbWZwBnoT5B68rIr9atisFT0=,tag:o5oLpO7YfPKTQkXAxQM1yg==,type:str]
    replication-password: ENC[AES256_GCM,data:SaZPkyrndNM6Ne7ZVAQ=,iv:NpPpZr/JJ7vs4GrS2eUd1dFdZYWUkzMNEwQooKkvAj0=,tag:FZ6CFnRVYYSS0hCQRNxW3Q==,type:str]
    postgres-password: ENC[AES256_GCM,data:X9bCJdXjwIyueHiLg2M=,iv:0ZSvw0qu6H5tFTHf3zvrU8wIqHRcMqXPv0MCexIDvfc=,tag:Kq/+oamrGdSZNaVuESeseQ==,type:str]
    app.token: ENC[AES256_GCM,data:avELVCytKncl8pUdByMY3rsuVLGREys4rLSSDfRidZk=,iv:3j5l6pJoMuJoOf29BHImkUD9v5hwBMlatl4lO1e9J8Y=,tag:sB2m2WUrHIufM/3s99c+7Q==,type:str]
    app.password: ENC[AES256_GCM,data:IEBippQSObJO0slOAGc=,iv:e+hnyxOFkRGnpnyXTek+qI3dnx0rJqrdUu6xFYE96q0=,tag:kyUmBVpZvVOqghsAwa/YJw==,type:str]
    app.postgres-url: ENC[AES256_GCM,data:Mog4YY1ymP9zv5f39IuPnujDgku/sl3db4FO5e3R3MgmPfFKyK5TWZN6mkQUPCbMTexkc1rzoAfv02d7n1qhMS5tHr/M3JrNH9aCcNu7DQQvcEvcpOnc0naK+RkpDV2BJfMNmoNp8r1qbWLqX3RfYjjiRzniyA==,iv:dflvMlsQmc8VBxP2SgIPkLPZc0INkLhf4qGSlK1akAc=,tag:lVuQhKdLVuAqRbuw4kcY2g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14j28wpn82nnskt0rzcaqxzwnhx33ardgl640rckvwrys8grphvwsyt4ch2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUjQ2NmtLQ1JKVEgwRkdS
            MVZTUnNZWUsvUS9MVWpwb001bXd3L2lJSlhrCkJFajBHNzVobnRWNU5TV2swYnRO
            dEIyNnRpVVVTK01YWU5wZTRPbGN6Y1EKLS0tIGFwYno0aCtybXBLVFc1L2I5VFlB
            eGJtck1sVEVQMi9nZWgvS3hJTm9KWlUKCUUgCNrIGhAfvkFpfoSbyE8y37MS5Bww
            ET2BH5lqLdq35hGdU0jubOFrk4iLyC88x3YEyuIOjrHdf9eCLfQM/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-28T08:45:19Z"
    mac: ENC[AES256_GCM,data:aI5bnv/ysclbzkARJ3EgKShkRxb8FWO22auMg3l1jWiTdhtWLYXM1pS3RJwe2sIalHQ7+x/JFIk17h8OR9OPi0L1CRieJK5VF51r8FVj8YSi1QoEqbzx4e03BqNIl6azWzOSk4YvpdLkihtjLu2jbgQqVH+Va2j5vRxI0lLeg2A=,iv:i0trBC/LGcWDH8lnUBYKF4O7HRXKzjqKAZx2cxjnVnY=,tag:ixAimUrGWbpDFvmf9O2S6A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
