---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: comabase-db
  namespace: comabase
spec:
  interval: 15m
  chart:
    spec:
      chart: postgresql
      version: 12.5.9
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 15m
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      postgresql:
        auth:
          username: vietwings_comabase
          database: vietwings_comabase
          existingSecret: db-secrets
    primary:
      podSecurityContext:
        fsGroup: 65534
      containerSecurityContext:
        runAsUser: 65534
        runAsGroup: 0
      persistence:
        enabled: true
        storageClass: home-cluster-nfs-1
        size: 20Gi
