apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    api-token: ENC[AES256_GCM,data:otzqtwLw0h5UHSDtpU8L3ylkaBmf9+A/Lf6e98Gmp7x/anyxJ1VSFw==,iv:ZYDKcGbaMKEZPpUxf/IduSVsr+EqNX7iLCLt7mHEQBs=,tag:L8XOhzpBlP4cus762VOH9Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14j28wpn82nnskt0rzcaqxzwnhx33ardgl640rckvwrys8grphvwsyt4ch2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWSXNsZ0J0MmFVYzhvb0Ns
            YlJncXY0U3BvclUwazM2TUthWGpOWlpoekdrCk14VGRvZUEyN2NVUVVWV2M4R1ZW
            d1h4bFh0TXJEVVF5ZFVnNHVoZ0cwNDQKLS0tIFZxSHIrWU9GRS9veGpuRXZkZEZJ
            K21DSm9UckdaM1BrWXZ3bmRhUXRyUEEKJw33/8Y0S+ap7Szskg/cGsQbrezKoC3d
            CYyPy+ozk1Ynx6/rhlFjmKrLNR17cCBaVFpiydotQgmAKMUKF1OyVg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-23T08:44:43Z"
    mac: ENC[AES256_GCM,data:YchMUY9RCay9RXSpqL8nEHdMKTqdAzQxvfnP/ga+tFcCR24UmrKtgBORqha0Gjl7iUC4A1SzzNJODh5Nc2GvmBpZ/cpkOf3RcGDMUaxc4DiZzqvJyrcOUSB+Wj+89H4yI34Hv74Ip4s5rRF0RPe3DHwuYoBu6FuMEV75stqGYNk=,iv:jEGaVtNRyJHe7ELwGVxwBy0yjegZRocZQ/cwlabwQgU=,tag:fv0lng4csZgSgO7A2TAssQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
