---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: seafile-app
  namespace: seafile
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        strategy: RollingUpdate

        containers:
          main:
            image:
              repository: seafileltd/seafile-mc
              tag: 11.0.1
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
            env:
              TIME_ZONE: Asia/Ho_Chi_Minh
              DB_HOST: seafile-db-mariadb.seafile.svc.cluster.local
              DB_ROOT_PASSWD:
                valueFrom:
                  secretKeyRef:
                    name: app-secrets
                    key: mariadb-root-password
              SEAFILE_ADMIN_EMAIL:
                valueFrom:
                  secretKeyRef:
                    name: app-secrets
                    key: app-admin-email
              SEAFILE_ADMIN_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: app-secrets
                    key: app-admin-password
    service:
      main:
        ports:
          http:
            port: 80

    ingress:
      main:
        enabled: true
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        hosts:
          - host: &host "files.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http

    persistence:
      data:
        enabled: true
        globalMounts:
          - path: /opt/seafile-data
            readOnly: false
        storageClass: home-cluster-nfs-1
        accessMode: ReadWriteOnce
        size: 100Gi
