---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: frigate
resources:
  - ./frigate-pvc.yaml
  - ./secret.sops.yaml
  - ./helmrelease.yaml
  - ./gatus.yaml
configMapGenerator:
  - name: frigate-configmap
    files:
      - config.yml=./config/config.yml
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
