---
# yaml-language-server: $schema=https://kubernetes-schemas.haraldkoch.ca/postgresql.cnpg.io/scheduledbackup_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: daily-backup
  namespace: dbms
spec:
  schedule: "@daily"
  immediate: true
  backupOwnerReference: self
  cluster:
    name: kochhaus-v15
