---
apiVersion: v1
kind: Service
metadata:
  name: &app postgres
  namespace: dbms
  labels:
    app.kubernetes.io/name: *app
    app.kubernetes.io/instance: *app
  annotations:
    external-dns.alpha.kubernetes.io/hostname: postgres.${CLUSTER_DOMAIN}
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  externalIPs: ["${SVC_POSTGRES_ADDR_V4}", "${SVC_POSTGRES_ADDR_V6}"]
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    cnpg.io/cluster: kochhaus-v15
    role: primary
