---
# yaml-language-server: $schema=https://github.com/fluxcd-community/flux2-schemas/raw/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cnpg
  namespace: dbms
spec:
  interval: 30m
  chart:
    spec:
      chart: cloudnative-pg
      version: 0.19.1
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: local-path-provisioner
      namespace: kube-system
  values:
    crds:
      create: true
    config:
      data:
        INHERITED_ANNOTATIONS: kyverno.io/ignore
    resources:
      requests:
        cpu: 15m
        memory: 128Mi
      limits:
        cpu: 15m
        memory: 192Mi
