---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: langflow-app
  namespace: langflow
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        strategy: RollingUpdate
        containers:
          main:
            image:
              repository: aitbase/langflow
              tag: v0.5.5

            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: &port 7860
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false

            env:
              LANGFLOW_DATABASE_URL: "sqlite:///langflow_data/langflow.db"
              LANGFLOW_LANGCHAIN_CACHE: SQLiteCache
              LANGFLOW_HOST: "127.0.0.1"
              LANGFLOW_WORKERS: 1
              LANGFLOW_PORT: *port
              LANGFLOW_OPEN_BROWSER: false
              LANGFLOW_REMOVE_API_KEYS: false
              LANGFLOW_CACHE_TYPE: memory
              LANGFLOW_AUTO_LOGIN: false
              LANGFLOW_SUPERUSER:
                valueFrom:
                  secretKeyRef:
                    name: app-secrets
                    key: app.username
              LANGFLOW_SUPERUSER_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: app-secrets
                    key: app.password
    service:
      main:
        ports:
          http:
            port: *port

    ingress:
      main:
        enabled: true
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        hosts:
          - host: &host "langflow.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
        tls:
          - secretName: "langflow-app-tls"
            hosts:
              - *host

    # resources:
    #   requests:
    #     cpu: 100m
    #     memory: 100Mi
    #   limits:
    #     memory: 500Mi
    persistence:
      data:
        enabled: true
        storageClass: home-cluster-nfs-1
        accessMode: ReadWriteOnce
        size: 1Gi
        globalMounts:
          - path: /langflow_data
            readOnly: false
