# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: app-secrets
    namespace: windmill
stringData:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:Fma9DvJSoPbEFJYXpnY9,iv:dQ3i3QTRoOJ5Oo/5spTK1TKSKcult8SuMn8AzmC8iv4=,tag:7CGauPd3k20Rvp/PDxF33g==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:Bt9kWnlAe58yTPPXUQpc+VcAWESwiBALMLz3lvcRvqyu7408qpNkblGksHMUs9kD4iU=,iv:Etw28t71S+rDIwFQaR+8GmjGJXbzPYIUddbgXy2e8qU=,tag:uv93PgCzEM3yeB7QsiFffg==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:zgWeCNxyeKI=,iv:vozxTS/hBfmIHGDCzHXjkaGPIjlU2RPSwcRKIB2NkEs=,tag:QNur4Ut9F8yggL+4aMTyDg==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:WrgQVOjs9iBqy6wsxwXItw==,iv:wNnOkQmUAEyrAAyKkUufnsATzawtHoWcXj0IOySyHT0=,tag:kstsysSymuR0Baw0KboQIw==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:2ZjbOATDEmvD2cACjDw4dQ==,iv:anFN7xUU5TnR/XpSScq5MDeRWLh90Ro807CKmJCwaZY=,tag:jTpiD/9Rc0Hh2Y/KO9esKw==,type:str]
    replication-password: ENC[AES256_GCM,data:wqN/BxEuZvig3IsPHWuiIA==,iv:Trq+guQlUT7PnPrAQyQi6+AhU1SQw6FwSIdjpHqPoOE=,tag:RluO/TPlapK205Aeg84bMw==,type:str]
    postgres-password: ENC[AES256_GCM,data:ttW82ztvKUCUUwVRuPeZNg==,iv:kKM0CxE9oB8AqiMK2zlU8crDEvS8+yFgqw/xOXztjMs=,tag:a0N14iJDMM9VznU/Xq72mw==,type:str]
    url: ENC[AES256_GCM,data:tlFU1Q+oPpD9AN4qvipv+m8bSi8p5hFwWsU/y5nIQgCI6ZZILcqh27P1UgZ70OwfUXjQE2zuVtrA/SLQPdE/uXnIQypmmnDQaHOQpi0XqhMDVEl3EwEUbaM366orL8Rlhb8Ile+Kb1pHFs9vHXUFQRw0vgg=,iv:gbLYUFu1wEb5PAw2+OkQgd88jiaqIMk0bNKmOXL9s/s=,tag:1w8lmxerK8FLjlv365ctOA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14j28wpn82nnskt0rzcaqxzwnhx33ardgl640rckvwrys8grphvwsyt4ch2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrNHFiNk5rUEJoRnRxWndk
            MUVhVHNPWnlVTVduQzlNYk81Tm5MRW01VjBBCk9JZ3kzbVMzMU9neXBKa2dBMkJq
            TVMwakZEWitKVURFV0ZQelFmUW1QVEEKLS0tIEM0dE13TWc2bGFJMVR5UmdaMFpQ
            NnVlTEZzcWdUdzlkdjhVMjlXK1pvYVUK2k8S5U8PZ9R3HnBg8Tf/elTzkwlnSXjv
            X7sAZTqaPCu/HupqWeqtV+xmvpNys37B4r3SDNCZzo+HWkvUfolj8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-08T03:18:29Z"
    mac: ENC[AES256_GCM,data:yxVNk3gABO8UGBdm+85O3YYvRqm/jlUU9v1iP5JHzVySZtKVyMlRI4fPWBJaDD8r+KnZKULvmfDkMJf934I9kX0WYeJnqeZ0CaW+C3pAoF6Z2waxilwdHuMMzSQ6rmy6PMcHr6926ihkYzz9iskJp7Nag0xpi1iDpbWZfRROpyg=,iv:c1Yrf9kcWivDDrgzK4HmTTkt++gyq+M6h8/ptXA5lds=,tag:S1CaM3pBYBuF6Zd8omcztg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
