---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: comabase-web
  namespace: comabase
spec:
  interval: 15m
  chart:
    spec:
      chart: comabase
      version: 1.0.1
      sourceRef:
        kind: HelmRepository
        name: imtoanle
        namespace: flux-system
      interval: 15m
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    hostNetwork: false
    env:

    image:
      repository: aitbase/comabase-web
      tag: v1.3.7
    service:
      main:
        ports:
          http:
            port: 8080
    ingress:
      main:
        enabled: true
        ingressClassName: "external"
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        hosts:
          - host: &host "vietwings.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: "vietwings-comabase-web-tls"
    persistence:
      config:
        enabled: true
        type: "configMap"
        name: "web-config"
        mountPath: "/etc/nginx/conf.d/my.conf"
        subPath: "nginx-my.conf"
    # securityContext:
    #   runAsGroup: 1000
    #   runAsUser: 1000
