apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
stringData:
    password: ENC[AES256_GCM,data:7ZQn8GxQP6O+wbaN2jmizv0mQ1qc0QCs4Zl5p3ohDfJCRMq6X8hjQ9ConQSAcL0o2rNlPFz2C0HRT4/v,iv:iA8VK/NNcaoTb90/uTxqDisECH3XAKSOoaXiPgr02k0=,tag:cigA+C4oGo40oxmp73OF4w==,type:str]
    username: ENC[AES256_GCM,data:OtKjHv4=,iv:5hJ7ZPxlvH3jHHsLWYH2aQZH5r0PijNRGQxwbxuwGWA=,tag:1/ZZ+gipXadOQvHyuM/T4g==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14j28wpn82nnskt0rzcaqxzwnhx33ardgl640rckvwrys8grphvwsyt4ch2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvaFU1UCt6RFNtSWsrNzJ5
            aVlUSEJGemVNQXB0dU5EQlpCSjNoeklRM0NvCnduKzVEQ2c5eTlzS2JUUTFMYUlo
            bVlZY091WlRpWU9jd2tqZ0JJWFFtWVkKLS0tIFNWaXZsQzFERFlFbUF3dG90bTVt
            MDVVZlpCZ05RdnBreVBYWjlIZ1d5SUEK3Xe8cWVYc9pxDbhCX3d73q1zICb4esCN
            rZesW+c89pCsjGAYf/cHqyTBFBBF3vZDKz6FVHTISHHZLkD58puK5g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-23T08:44:50Z"
    mac: ENC[AES256_GCM,data:gkNLC3zKsux6PuFjy93sW1qbJumckHXNt4gyJ9sJz7pt1ViK0x7xq5Ajvv4VsXDKJq9EToIvQII5ha0BZJlAOeuXjT9dEjrlK5u4wAeiVmSJHcuxjlOhY2nIzq+ismo90yt+J5+gsN9azDJJnggXTNWhtTasCt4G4hORL63YcgM=,iv:9IMz1bTPXRTxfGE1h/07A7MkWdiFn7r/chuNJ72kOxk=,tag:3kpVgaTZMCb1VbbGIyyzdQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
