apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
stringData:
    password: ENC[AES256_GCM,data:R7AOPA+IGzePSZaLQOFuHQIvnELxvHABwAb9AnAHalOWlDiSqm+9t6Ei5TiIV38fKUMFoHZtKxAzJRy3,iv:MEKcX+RBVPWSLbbjvE3uBfSqVNahGV9lK4MZIxaX9Wk=,tag:23KqabQVR1UvsllY4d/b0w==,type:str]
    username: ENC[AES256_GCM,data:suQ7EfU=,iv:5mHIaUk+t/BC7GAUjIFApVjdeoZU/LA3LAm3nItAgSU=,tag:WdX2sFENYzasOGXLxInYiw==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14j28wpn82nnskt0rzcaqxzwnhx33ardgl640rckvwrys8grphvwsyt4ch2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4bUVnMVhFVW9WekxwV0pS
            UEJvcVVORElUK1NBRUFrYVdickhFTkJxa0c0Cm9BdHUxT3ZYbllkaVgxbjhrR2dy
            Q0hWUGdFNEtJN0VjY1FnWHh0ZUFsTFEKLS0tIFpXL2ZlU3RtNWp5VEdmdkVqL3pZ
            VzFFaHlScTlaZ29LSEpCZHNjK280NTQK8T09HHL0O5VJ1l7D8hitZXzxbAiwPsvh
            +mS5Jn296Mx7gQZ7tpelM8ybcpEGtK/ySUIPQmullqTJXdS646RsEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-23T23:54:00Z"
    mac: ENC[AES256_GCM,data:43vFF+gbg1WH2lVo0U9JfxmKA1RfAJ86oI21AZRLeIdgefjn+GEYm4X+luv+MZ59cBEKcBHTF9tWIt7ZKwzy55Xbp41jgbPVHSmKWa117txHiXbniMFReOQE9DzxHJdI7szPkVNfOJg73+6g/O6NcTSi5aA78bfKdRYwGlVxnso=,iv:yc58IWoN2TZur+Owgl979mdQlShW03ESedjbFCmtvXw=,tag:Lwcxn2849EoSyIRnIkuS7A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
