---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${SECRET_DOMAIN_2/./-}-staging"
  namespace: networking
spec:
  secretName: "${SECRET_DOMAIN_2/./-}-staging-tls"
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "${SECRET_DOMAIN_2}"
  dnsNames:
    - "${SECRET_DOMAIN_2}"
    - "*.${SECRET_DOMAIN_2}"
    - "*.s3.${SECRET_DOMAIN_2}"
