---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openproject-app
  namespace: business
spec:
  interval: 30m
  chart:
    spec:
      chart: openproject
      version: 4.0.0
      sourceRef:
        kind: HelmRepository
        name: openproject
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    ingress:
      ingressClassName: external
      annotations:
        external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
      host: &host "openproject.${SECRET_DOMAIN}"
      tls:
        enabled: true
        secretName: "openproject-app-tls"
    openproject:
      https: false
      host: *host
    persistence:
      enabled: true
      accessModes:
        - "ReadWriteOnce"
      storageClassName: local-path
    postgresql:
      bundled: false
      connection:
        host: postgres-rw.database.svc.cluster.local
        port: 5432
      auth:
        existingSecret: openproject-app-secrets
        secretKeys:
          userPasswordKey: "postgres-user-password"
        username: openproject
        database: openproject
  valuesFrom:
    - name: openproject-app-secrets
      kind: Secret
      valuesKey: values.yaml
