# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: openproject-app-secrets
    namespace: business
stringData:
    postgres-user-password: ENC[AES256_GCM,data:a4dDkoDSl70WnIkdF+MaVQ==,iv:44Ex6WwlJRnHwfQuAaxNnVnc7Fh7qZ3G31FmClKxvMI=,tag:Jn7iTHb71zmrTOTZG8PGow==,type:str]
    values.yaml: ENC[AES256_GCM,data:b2aUz5nc1SaK8wr7OmLNAt68SAEnaMH+5+5o0eVMu8D67DFJ1NaTiMc4VKH8O1dGisQoJX7yF1udVAqGA14Up8sSPIyXGv+jcPO6BIL6dT/DnfIN7hbyKglBbyLw17EosvlaXFfVYGlWVT69oiC2BMZg,iv:d06p4E5JqwUBgvOzESOctBo2A/VPWu1855y/sr6PVsM=,tag:HDh4JIlGmRI/+TGyjAzowQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14j28wpn82nnskt0rzcaqxzwnhx33ardgl640rckvwrys8grphvwsyt4ch2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUjQ2NmtLQ1JKVEgwRkdS
            MVZTUnNZWUsvUS9MVWpwb001bXd3L2lJSlhrCkJFajBHNzVobnRWNU5TV2swYnRO
            dEIyNnRpVVVTK01YWU5wZTRPbGN6Y1EKLS0tIGFwYno0aCtybXBLVFc1L2I5VFlB
            eGJtck1sVEVQMi9nZWgvS3hJTm9KWlUKCUUgCNrIGhAfvkFpfoSbyE8y37MS5Bww
            ET2BH5lqLdq35hGdU0jubOFrk4iLyC88x3YEyuIOjrHdf9eCLfQM/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-14T08:48:30Z"
    mac: ENC[AES256_GCM,data:rqLwRgUbpE0Erd/zrr3keq6PTcKZeML98OE11i7ovNKr9XXCHP2dUCPXABfS1Tb5FoSmMmNHXA/QBxCMPDWr4C+F+a0XGJUPNWjE7uQCUJapv6m7InElYXCy++QAlQ05BMBEYAIm8MdhPXJNHrJ8vwU9sTd15h3uDy4zC07g8zw=,iv:VqDZ4CCsvSMCc2e5887mmPfmNqt7gx35G1LgoKbsRqY=,tag:WA7rkv1xnJmPim1dVA/qAg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
