apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:sSt0pmUd+Sxeb6ObqJKYcfks,iv:SXjN2/nom84ycT2YzfP6QU/9NsAij14Xd5QN+Huj5HU=,tag:Le7RoNZ4wFVkqSOFvHuHWw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:vLIyHLi5RabaHedHK5uE0HAltbNfFiqBmXotCm2Rgy0yNqi7,iv:AQBf84F0EzrlH3QQffS0gWA8gWCsnicgO5gk6TzykZo=,tag:GbUFzvG5YaumYtt0L++IYw==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:NShsK/JMxzWzvog=,iv:dhhFiPVrK8zssReYxmyFro6CivDde1OmHr6rls4GtQE=,tag:Qp1Q6Or+xbfj2eMoyn+ozQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14j28wpn82nnskt0rzcaqxzwnhx33ardgl640rckvwrys8grphvwsyt4ch2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnc09qa3FmU3EvQVcwOEUy
            L1kyT1dqYmsyV2dEOXFIdnAvN1dZdDFlWDBrCk9ZWmtIU1FlNG1OR1krelEvcEVz
            Y2xuNDFVQ21mVlZiUGFHcnNaa2FIeEUKLS0tIERNTGw3VXA4RGV0K2JNVzZPYzdI
            anY3MkllY0UrY1Rzei9LUDhDRXV4NjQK45OqcE/ZUi85FWLj82gDPv8Xcy83glWy
            mIG/TXZftDjTL60BfQcFt2FDZK+yxJ+rrFhLDLNwDzH5+N9f3pHfuw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-23T23:53:53Z"
    mac: ENC[AES256_GCM,data:NJqQXrzfK/gt2yc+X3fOvX7EJbw2oFpWah4T4arxFkiFMqofHWAAqq3xSFC2f3AxiqWT6hPzAs11lZoLgfFWYmPrBh2tSE/YeGtTLC+S1njVNXVLpE7+JYBGkYHgNyYZP2FOcfEqbRS9y6S4pybySSTMgzCKFh7yuBey0GskErw=,iv:z7wIngXUC9xKyCcS61KGDvfMeDel6UBLAauQWzBdjoI=,tag:yISZ+0UrTgURkSFALFYK/Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
