apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:ytAAaga0CmhHCDcf2J//azrJ,iv:1VFvZqmM65GjK6CjIv1JnYw0vijt5l/sYN21ExAXDXg=,tag:Oy3w3azJryiimhgb9IZbUg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:rI+Zr6f6Ap6rz2OM5lY3DKfq08BfFjdRX+oy14oGBgSQLKcK,iv:XldU1awlX/hr+C2MlWaKgkpGsbajxJnCvUeOPSB7t5s=,tag:nP2h2Hu/xZpIQdJe9K3vtA==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:0FmLymsZi9ngwdrAAQ==,iv:7qQuJhYoZ5bA+9toCkm5o01tY2QqAvrdG8rSOQYsxaQ=,tag:jR4it6FzLXTDTDskvDkiug==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14j28wpn82nnskt0rzcaqxzwnhx33ardgl640rckvwrys8grphvwsyt4ch2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoNU44SmN2MUZLN05aRElG
            dzZGVFVsK1VQRk8yS2ovYU4zdS9rNmJldHdFCmYxdmZOM1VOaUtSMkRQdHVrUWdJ
            ckQ4ZVYxSCt2N1lreTlHb0Z2d2p2b1EKLS0tIG54ZjRPa3VITUtERUhSSnliemJS
            a3lGSG1zcDlKNVVwY1h2cUJyc1F4ZHMKpRywPZz9vSLO4lzy2eJh1s9TlB/tAmIV
            yTJhyFj7IDnnjhiG6pX4IemdMxmgbj3HDg6aVNrx5ycGlU4HuIRHeg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-23T08:44:43Z"
    mac: ENC[AES256_GCM,data:jcep2UdJJZ+qpuLPFJzBek95sksDtfnI2QeLkp4KWXmptLjj8NAwsRpSuwg++/BoG3QR+pcBsVlVueRi3UNmb7NeRMHN6FMmozIDZUSnefdVQevSSn2QNNkmvTPkTwwvnZRvpSYrvyxze/TPrjlmSBjSGotie85WgI9QE7LP0kI=,iv:eOF06AfgAy4VdNjE4vkMbXOHeftzP+BGyhvfFO1mjHw=,tag:jCngaUs1a8wMjdWyrRlClA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
