---
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-gatus-ep
  namespace: monitoring
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: loki
        group: guarded
        url: http://loki-gateway.monitoring.svc.cluster.local
        interval: 1m
        ui:
          hide-hostname: true
          hide-url: true
        client:
          dns-resolver: tcp://${COREDNS_ADDR}:53
        conditions:
          - "[STATUS] == 200"
        alerts:
          - type: pushover
