apiVersion: v1
kind: Secret
metadata:
    name: loki-secrets
    namespace: monitoring
stringData:
    BUCKET_HOST: ENC[AES256_GCM,data:BKPjYeKWAYM0k/PfQEiLbfmVo+oI+qDdQ1Wcc2U7trfdr2fHHRKrjXbrOJn/hzeA5bZ5SVySYAcFHjNsJJY/fA==,iv:KTDhGXTdfg0HrmIdBh5QffBk27+VJaGvxfcY2OQAHNQ=,tag:8zBJAxkHmybbTxtAS5+xiA==,type:str]
    BUCKET_NAME: ENC[AES256_GCM,data:SGTTsw==,iv:DJxZQsQjhuTk2gCiOJ0kJiSU5SwuKnq4AZ7bMD/i5gQ=,tag:gmozc/nEv/UpDSeXlwu3PQ==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:AB7ReJ5bFRhhr/BfOlRyYGTYB8LrZ1DnhYNTw5XsrXU=,iv:DPhmteSIPXAml3FMTs1vVmm0Qzz7cOQEZ8Ybalop8HE=,tag:JXfUJ3ybIqrAt8t9xtWGFA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Rq7fNIuUISkwJDaJSGrCuYBDHxk5LChHiK5jZ3uIo4euLCBf/0PFQ60UwgmVHxUZf5Fq7ypiGIAgdKAr+MkBHw==,iv:JA32OUBWnffPZ/1kInrBIjs9b5kxLE2441oX7IUCerc=,tag:G0eE48WPt1drnFEm9KXUbw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14j28wpn82nnskt0rzcaqxzwnhx33ardgl640rckvwrys8grphvwsyt4ch2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOeXE5VWxNc2dPUGU5Qy9N
            K1JKd0RBSUUyNDZsNzZMZnVIWkFmMjN4dEVzCkZlVCs0bHRKV2U2WG15RThCS0Y3
            NWZKdllOSU93TmJTR25PRTcvL2RkM3cKLS0tIFBhaDM1MThQaVZIUU82OHpWSVFx
            RFZyZlNoMDAyMzk3WnFCUW0rbHhUdHMKrYogU2qfMZfFBvm7GE3PXWuDsWth1Xon
            DZ8vpJjBGyuc23eFN0QWzkNHDW7AU0Kgu0taHrio5IG7BcZCwYTqDA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-11T05:22:49Z"
    mac: ENC[AES256_GCM,data:pOGprGQNSJ+iLbkW/U5nvx2zcpGIlfarmxDCerNxbKgYB7lCQ/h9Q2l7cm3vg9M9J/wOoMxycBRUz3alrQFw1/PQ39LKe+YChQKuAkMpraGbgaiJbS0pH+mPYTqjICOgN3A6UCM+37f6E2gDquKUMPzmnE/S6ZK8kxD4AAImXzE=,iv:CGnsUvlr36LLDJDAHcK5rQFLH4egNHMxOh41+eK8zFQ=,tag:n52Mmtp6EX5VDJXZo/f67g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
