apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:YeGspN0JcpUGMncfMxM34817p8HZ1sKdK6UiRL4Dyh/VwlKd,iv:/qwFJ/IuRqTWp3frsIqBNxtKDZoO9gK+37edHEocqYs=,tag:IEXIguV+RfCEQQoKUzYR9Q==,type:str]
    credentials.json: ENC[AES256_GCM,data:Ib6KpPz4A3cIf5GsbPF9jaHglQm32UScAIdirNGLrrV+yHobup1x/xAUTFP+F18oCElrljBsmrHQb4E2E0ODEysr1btYbMXRMx1jYsrLKzLU0Ba5T4mL0I7r1eFIGq4k8bbS7WIwHiRsa0RuzGXnaTGASZFk4jssxSKQAVSBGyjtX3vm3EiiKFlj0mMKLBQRB0miYG1z5cvEZml85sSqRjc2Rog+YbIvSIP1I8h48Q==,iv:pPaBtyOH3ILD6cQVu0OnWjQRR2fs/3sL2wCrxYvIy2s=,tag:NyD7jbw3xA1V+eBcX7bN0w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14j28wpn82nnskt0rzcaqxzwnhx33ardgl640rckvwrys8grphvwsyt4ch2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHYXJ6alpkb3poaGNrMDlI
            VjNqdncvbU9NRFF2Zk03aDhScEszTkRKQTBRCkhnMjJrbFk1NmZWaUZoTlNyZ0hh
            VFg2NXhKdFhFVm1lZGdBMEd2bEI2Y0kKLS0tIDZxd2tPVWFQQWltVkhrbnJRdFdO
            MlhNZWlZUGc3S1ZSYWNiUmh4MUJwRnMKyzH3EW9APFoGEy73Da8wVQu2m0Zk5jJX
            Z9XfJkuTfTSoApZO6fehT60yUsIoqN5mI0IKNJCl4exVWgw4nQr//A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-23T23:53:53Z"
    mac: ENC[AES256_GCM,data:C4wXkrZkc5+HFYApHSrVgkRzw0Kqy/FhCi2RWuFGBi5bdR4YC5DqWrrPRCLSmPMzULyK8WWOdB0gGv6DhYGjnhzSYmVamW7ArlVbK7y6x079+27nFOA3uVInzXUx2XxRZsfUdep1USZ+V3SsrnVv4Q3SOKvFAviBwHQWZhvsRPM=,iv:eP66Bj9xpJJGfJWRQjQrgpAfwcr++FfUydJqXd+Jjbg=,tag:JCc0ANwl+z0t/eTazW/7ug==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
