---
# yaml-language-server: $schema=https://frigate.devbu.io/api/config/schema.json
logger:
  default: info
  # logs:
  #   frigate.record: debug

mqtt:
  host: mosquitto.broker.svc.cluster.local
  topic_prefix: frigate
  user: "{FRIGATE_MQTT_USERNAME}"
  password: "{FRIGATE_MQTT_PASSWORD}"

database:
  path: /data/frigate.db

record:
  enabled: true
  retain:
    days: 7
  events:
    # Optional: Number of seconds before the event to include (default: shown below)
    pre_capture: 5
    # Optional: Number of seconds after the event to include (default: shown below)
    post_capture: 5
    # Optional: Objects to save recordings for. (default: all tracked objects)
    objects:
      - person
    # Optional: Restrict recordings to objects that entered any of the listed zones (default: no required zones)
    required_zones: []
    # Optional: Retention settings for recordings of events
    retain:
      # Required: Default retention days (default: shown below)
      default: 14
      # Optional: Mode for retention. (default: shown below)
      #   all - save all recording segments for events regardless of activity
      #   motion - save all recordings segments for events with any detected motion
      #   active_objects - save all recording segments for event with active/moving objects
      #
      # NOTE: If the retain mode for the camera is more restrictive than the mode configured
      #       here, the segments will already be gone by the time this mode is applied.
      #       For example, if the camera retain mode is "motion", the segments without motion are
      #       never stored, so setting the mode to "all" here won't bring them back.
      mode: motion
      # Optional: Per object retention days
      objects:
        person: 15
snapshots:
  enabled: True
  timestamp: False
  bounding_box: True
  crop: False

ffmpeg:
  global_args: ["-hide_banner", "-loglevel", "warning"]
  hwaccel_args:
    [
      "-hwaccel",
      "vaapi",
      "-hwaccel_device",
      "/dev/dri/renderD128",
      "-hwaccel_output_format",
      "yuv420p",
    ]
  output_args:
    detect: -threads 2 -f rawvideo -pix_fmt yuv420p
    record: preset-record-generic-audio-copy
    # record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac

objects:
  track:
    - person
  filters:
    person:
      min_area: 2500
      max_area: 100000
      threshold: 0.75

go2rtc:
  streams:
    frigate_door_hq:
      - rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.1.100:554/cam/realmonitor?channel=1&subtype=0
      - "ffmpeg:frigate_door_hq#audio=opus"
    frigate_door_lq:
      - rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.1.100:554/cam/realmonitor?channel=1&subtype=1
      - "ffmpeg:frigate_door_lq#audio=opus"
    frigate_livingroom_hq:
      - rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.1.83:554/cam/realmonitor?channel=1&subtype=0
      - "ffmpeg:frigate_livingroom_hq#audio=opus"
    frigate_livingroom_lq:
      - rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.1.83:554/cam/realmonitor?channel=1&subtype=1
      - "ffmpeg:frigate_livingroom_lq#audio=opus"
  webrtc:
    candidates:
      - 10.0.99.210:8555
      - stun:8555

cameras:
  # Define at least one camera
  frigate_door:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/frigate_door_lq
          roles:
            - detect
        - path: rtsp://localhost:8554/frigate_door_hq
          roles:
            - record
    live:
      stream_name: frigate_door_lq
    detect:
      height: 480
      width: 704
      fps: 5
    objects:
      track:
        - person
      filters:
        person:
          min_area: 1500
          max_area: 100000
          threshold: 0.75
          min_score: 0.50
    motion:
      mask:
        - 513,36,680,39,683,21,518,21
    # zones:
    #   front_door:
    #     coordinates: 0,184,275,0,427,128,153,398
  frigate_livingroom:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/frigate_livingroom_lq
          roles:
            - detect
        - path: rtsp://localhost:8554/frigate_livingroom_hq
          roles:
            - record
    live:
      stream_name: frigate_livingroom_lq
    # detect:
    #   height: 480
    #   width: 704
    #   fps: 5
    # motion:
    #   mask:
    #     - 513,36,680,39,683,21,518,21
detectors:
  coral:
    type: edgetpu
    device: pci
