# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: db-envs
    namespace: seafile
stringData:
    ONLYOFFICE_DB_PASSWORD: ENC[AES256_GCM,data:Cj9/lvBiFfAv5oFmTVUB9g==,iv:EoyR4XFzcsEkCAkSXigvwS2mzkYyFX+QSJ2sojkI++4=,tag:OzsZ2AKBF7qw72iXIgshNQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14j28wpn82nnskt0rzcaqxzwnhx33ardgl640rckvwrys8grphvwsyt4ch2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2RzI4THpMMEtOM2ZEaFJZ
            OFdITEpTV1lJZ3NDTmRLZDFkOWtWU2hwK3gwCi85THg4cUdRLzFPamFYMjcyeS90
            VVk0cUVZSlkrcXM1WThBQStFam1lSEEKLS0tIFFHSGtTNWVqRUxxQnNSTC8zUlE5
            bWdJSHVEOEhWVEhzYXpUQWpBd3A4a28KYCNf5iuKmZ8pKMAIJ2bBV5J8l95wuTb8
            Wt8+3HIsI1wQtBff0ToNBa9L/gAV0iuU3bynYzCnG2+999C4dHS1MA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-30T03:45:18Z"
    mac: ENC[AES256_GCM,data:OwCVi4Wuo1nNO9CXDt4w2cM8LSDjXK5vCdqQiJmTdm/0ovECYUhsT30nmcAiFvG2NJnFh9reeEWEkg+POaA6jLV5cSLwFOlCHuY+pk54yYb/b0+Yz72VVBLHpT/c2Tc207nG3hp7uvo36zqUdJYZI3548c+e3F4nnjFwm4KC4uI=,iv:ATO1uLoHo7rj5qUV9OTtG6BRFXOScsVReMKTXy3jZbI=,tag:LGKw7Mq4o5pPylkh1qM/Ng==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
