# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: app-secrets
    namespace: seafile
stringData:
    mariadb-root-password: ENC[AES256_GCM,data:tBEArej85QBvwUIwvawmUQ==,iv:YlZ2CgxLndihx6vdaXyr2o2J0cCd4eaBatMUI1OlALE=,tag:QomgRI/fd9Cb7pGg3ypZog==,type:str]
    mariadb-replication-password: ENC[AES256_GCM,data:eqXVYhAYyBfRmdp1Nitt9Q==,iv:E74Tli9zwfJX5T/kAaSDeAFKeTpeLevZAk1t+WALMks=,tag:aLfO4VuNjJGZbUTu6hBG/Q==,type:str]
    mariadb-password: ENC[AES256_GCM,data:B7TQOWeiKY3mHYNmbZ9rlQ==,iv:Id3LyNFlDsf79kvwkmZ+2usM3mG7fLwhly+r/d5XzvI=,tag:LQT/ALFJFpJbCLUXy7a3kQ==,type:str]
    app-admin-email: ENC[AES256_GCM,data:ShZGrfyjJYDZnoH2hSZ5YBBabQ==,iv:ygzbihBDOQQhmXZwI4uIVUptpf9hT3NONQSbYswvJL4=,tag:FktiLko0M6IJ6BY4romrWw==,type:str]
    app-admin-password: ENC[AES256_GCM,data:ETvLzfQCB2GKsujf29fS4A==,iv:fNVCld7m/optjBhcvE2i420TUAoyQmJ+LJDtRR9xDOs=,tag:DH9CNU7G+KI7IPwVDUKWlQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14j28wpn82nnskt0rzcaqxzwnhx33ardgl640rckvwrys8grphvwsyt4ch2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUjQ2NmtLQ1JKVEgwRkdS
            MVZTUnNZWUsvUS9MVWpwb001bXd3L2lJSlhrCkJFajBHNzVobnRWNU5TV2swYnRO
            dEIyNnRpVVVTK01YWU5wZTRPbGN6Y1EKLS0tIGFwYno0aCtybXBLVFc1L2I5VFlB
            eGJtck1sVEVQMi9nZWgvS3hJTm9KWlUKCUUgCNrIGhAfvkFpfoSbyE8y37MS5Bww
            ET2BH5lqLdq35hGdU0jubOFrk4iLyC88x3YEyuIOjrHdf9eCLfQM/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-29T06:46:52Z"
    mac: ENC[AES256_GCM,data:cQKNAmGYE84+rBW7EmSnafTR1QfUSEad3aO7UXf28LL+sWQEspaRo2zCGkt12vOutzG8bkBRZSL2kQAK3RaFdyn/dy+br9K3mQ/5iHo02HWjkQJmsA8sok60EouwUkWtEh1X9A2Qq7seIPdtIynSzcqro/O8CU1Oynxgkkkgmbc=,iv:feOs0Pgk97OzLonbMmm/CUDEnykkOSMlKsDk2k7dwKk=,tag:aAblZlaW9qFywY+pD7LF8w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
