# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: app-secrets
    namespace: seafile
stringData:
    mariadb-root-password: ENC[AES256_GCM,data:tBEArej85QBvwUIwvawmUQ==,iv:YlZ2CgxLndihx6vdaXyr2o2J0cCd4eaBatMUI1OlALE=,tag:QomgRI/fd9Cb7pGg3ypZog==,type:str]
    mariadb-replication-password: ENC[AES256_GCM,data:eqXVYhAYyBfRmdp1Nitt9Q==,iv:E74Tli9zwfJX5T/kAaSDeAFKeTpeLevZAk1t+WALMks=,tag:aLfO4VuNjJGZbUTu6hBG/Q==,type:str]
    mariadb-password: ENC[AES256_GCM,data:r8fs32MBuy4HOt3rVZVKeQ==,iv:GjzhkaZRzMwp2ALUyqJGX9EUU1ddy1szohFvvPQlWio=,tag:TPUkmbY9NR6w48hU0NCTig==,type:str]
    app-admin-email: ENC[AES256_GCM,data:ShZGrfyjJYDZnoH2hSZ5YBBabQ==,iv:ygzbihBDOQQhmXZwI4uIVUptpf9hT3NONQSbYswvJL4=,tag:FktiLko0M6IJ6BY4romrWw==,type:str]
    app-admin-password: ENC[AES256_GCM,data:ETvLzfQCB2GKsujf29fS4A==,iv:fNVCld7m/optjBhcvE2i420TUAoyQmJ+LJDtRR9xDOs=,tag:DH9CNU7G+KI7IPwVDUKWlQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14j28wpn82nnskt0rzcaqxzwnhx33ardgl640rckvwrys8grphvwsyt4ch2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUjQ2NmtLQ1JKVEgwRkdS
            MVZTUnNZWUsvUS9MVWpwb001bXd3L2lJSlhrCkJFajBHNzVobnRWNU5TV2swYnRO
            dEIyNnRpVVVTK01YWU5wZTRPbGN6Y1EKLS0tIGFwYno0aCtybXBLVFc1L2I5VFlB
            eGJtck1sVEVQMi9nZWgvS3hJTm9KWlUKCUUgCNrIGhAfvkFpfoSbyE8y37MS5Bww
            ET2BH5lqLdq35hGdU0jubOFrk4iLyC88x3YEyuIOjrHdf9eCLfQM/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-29T03:43:23Z"
    mac: ENC[AES256_GCM,data:ZEMCWczVnkVzXcd1+wPbF2prKTI1fugLiIbsYR4Cj3CZ412TJ+VNY+XkfanmNYb4XK+9cYkisdY/0d4WbbD2i8TRIrltWUIx3YJB/zwlFrQM2NZJNPiezlxXKCn5asS4MlUeXWnrAIascH5PdF2fTsUfColw9+O1dbCpSirSZzs=,iv:fr8/slPxQZE4iDqkJ/wCgl1zBK66B1xubfVzqBc39P4=,tag:5auXz0UKPgjAfmNZFjN6RA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
