# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: app-secrets
    namespace: seafile
stringData:
    mariadb-root-password: ENC[AES256_GCM,data:tBEArej85QBvwUIwvawmUQ==,iv:YlZ2CgxLndihx6vdaXyr2o2J0cCd4eaBatMUI1OlALE=,tag:QomgRI/fd9Cb7pGg3ypZog==,type:str]
    mariadb-replication-password: ENC[AES256_GCM,data:eqXVYhAYyBfRmdp1Nitt9Q==,iv:E74Tli9zwfJX5T/kAaSDeAFKeTpeLevZAk1t+WALMks=,tag:aLfO4VuNjJGZbUTu6hBG/Q==,type:str]
    mariadb-password: ENC[AES256_GCM,data:mCib5VVPBFYYD8sVQF4=,iv:bldvcWgHWjdJDVRG+bOzDuecYHWxpwwFDP7uQmYXRCw=,tag:67KUKmXc4KmR7lPEXk7X2A==,type:str]
    app-admin-email: ENC[AES256_GCM,data:ShZGrfyjJYDZnoH2hSZ5YBBabQ==,iv:ygzbihBDOQQhmXZwI4uIVUptpf9hT3NONQSbYswvJL4=,tag:FktiLko0M6IJ6BY4romrWw==,type:str]
    app-admin-password: ENC[AES256_GCM,data:ETvLzfQCB2GKsujf29fS4A==,iv:fNVCld7m/optjBhcvE2i420TUAoyQmJ+LJDtRR9xDOs=,tag:DH9CNU7G+KI7IPwVDUKWlQ==,type:str]
    onlyoffice-db-password: ENC[AES256_GCM,data:4vM3haJP6xYQ9McVyvk=,iv:K5kWwOzU+W+9nvgu7e7YSt4b2uVFLKLuI9pzwfJPdcc=,tag:7g8jV805CVVD1Tb5A+tGpg==,type:str]
    onlyoffice-jwt-secret: ENC[AES256_GCM,data:Lbnwe4aEbb99IKi8M/OHT2C+rkcakfwzp0pxN6dRgY4=,iv:ayrZT3JP1Oo6hWRySaeICxLBLUi+BG3YqmkU/kFqakU=,tag:CZIkwEQbOegAaf7fZlVknQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14j28wpn82nnskt0rzcaqxzwnhx33ardgl640rckvwrys8grphvwsyt4ch2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUjQ2NmtLQ1JKVEgwRkdS
            MVZTUnNZWUsvUS9MVWpwb001bXd3L2lJSlhrCkJFajBHNzVobnRWNU5TV2swYnRO
            dEIyNnRpVVVTK01YWU5wZTRPbGN6Y1EKLS0tIGFwYno0aCtybXBLVFc1L2I5VFlB
            eGJtck1sVEVQMi9nZWgvS3hJTm9KWlUKCUUgCNrIGhAfvkFpfoSbyE8y37MS5Bww
            ET2BH5lqLdq35hGdU0jubOFrk4iLyC88x3YEyuIOjrHdf9eCLfQM/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-29T23:55:35Z"
    mac: ENC[AES256_GCM,data:oo/EWpXePTLQWLM0ATSTp1RMRfLuIZzmJ/j2FIt0QLSn+dg2exN1wjZzcKDcIXV21wQMlt+eSFx/DKrrdIHmPMf0lpTo4EwAnA2eYLHaGHiRJVo4TD2sY0PNEx3nZMbVChGDpnIv4F3WawhU6Odrx0dI6F5PEdAECP+6qQjAqHI=,iv:7XfQb8cvRL1d5I2lpO1W22gcofRZruGfi/ixpreOGcg=,tag:a76PX4lnJwYitWeZ2TCJFw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
