---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mattermost-db
  namespace: mattermost
spec:
  interval: 15m
  chart:
    spec:
      chart: postgresql
      version: 12.1.9
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 15m
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      storageClass: home-cluster-nfs-1
      postgresql:
        auth:
          username: mattermost-team-edition
          database: mattermost-team-edition
          existingSecret: mattermost-secrets
    primary:
      persistence:
        enabled: true
        storageClass: home-cluster-nfs-1
        size: 5Gi
      # podSecurityContext:
      #   enabled: true
      #   fsGroup: 65534
      # containerSecurityContext:
      #   enabled: true
      #   runAsUser: 65534
      #   runAsGroup: 65534
      #   runAsNonRoot: false
    volumePermissions:
      enabled: true
      containerSecurityContext:
        runAsUser: 0
        runAsGroup: 0
        runAsNonRoot: false
