# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: plane-app-secrets
    namespace: business
stringData:
    values.yaml: ENC[AES256_GCM,data:lF4iMII+F+edEERliwZc+kVK7WE2f/6MnxrGfeLYhiMFKRyqbcTmoHoMCT5c+CarMuHlqTKv2YbMKHTjaFbAg3kKvIqMqtRoDhSKf1bZ7YUeKiAhYut5ds7qL2+rTELLNxufT487e7jMML6h3TOJsoGkH+JOWImLMpj119LmJB+clAPYq0Tup/VHDw6urj0WAWSeNMGOPsFtI552p5GVDhHgyTu8kyZcy4+t81Wrez0cg+bxpwacwHoWNB+uYYTg5hs2anNLgUyp6YTBtNLqn+jY7p0J5rbfnrDqxdUIr3PXCDS+jW5j0ic5ALjJOicBiyEAQrfX6Na9qwqjxP1q/81zJDny89tfgYTiu3O3MWcG3cpvPL59Ng2Dqxoo/lM0ApzbvNMKoxiToG3nXSVyk2u8JyUUeyZOJ1ifHn7BR47EL4koBzBNTyiyKWHu624+C/4kdrPm3+rD99hVnVMPLqBEBWO/xH7xkSx/ZmzDTaGIHzP2PpnpukL3z7XIsvAUHqtvfO11/q6eSepEsLPQO5jNK2bz0RBeiGdHJWWExgU5gUdpz56i0OW7jILALypPvhvjOBUxSkmKdmHizvMOH5FvzjXBDmj4ciXDht6fNMORJaekaVaDk8ShO49DSJpbjc4ZaXQ0NEwa8i7ttN781jbnaFBMMVcXCnXqCYT0H+vrs9FIL2bmVXW/sEYnZRj5RyhwNjbCU/Y/X+v7xZ/QXDx5WkXm9BHsbvfFRa5yohq9b3WHvS6CKhEcZFyZv/WtD0s7jDiu,iv:T4+roxgDx3AAkLWJionsYvAE9bolFJLByFrFwHYjoPU=,tag:wzfHClfNI1T73bFl4zYoRQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14j28wpn82nnskt0rzcaqxzwnhx33ardgl640rckvwrys8grphvwsyt4ch2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUjQ2NmtLQ1JKVEgwRkdS
            MVZTUnNZWUsvUS9MVWpwb001bXd3L2lJSlhrCkJFajBHNzVobnRWNU5TV2swYnRO
            dEIyNnRpVVVTK01YWU5wZTRPbGN6Y1EKLS0tIGFwYno0aCtybXBLVFc1L2I5VFlB
            eGJtck1sVEVQMi9nZWgvS3hJTm9KWlUKCUUgCNrIGhAfvkFpfoSbyE8y37MS5Bww
            ET2BH5lqLdq35hGdU0jubOFrk4iLyC88x3YEyuIOjrHdf9eCLfQM/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-15T02:46:09Z"
    mac: ENC[AES256_GCM,data:emIsbP1ZLFDdRsg1KMYl/zCyrgVzuFXlotoAAoyCDgf8teG9i3rrzfluzYsU7ZS5dvYR7sf5bNcEif5kgJB6fzfeKeCXSAsCMYEomSnkGtMPfEcn2ma5MUOLZ0vxPUbVqAlVjfw8yommKJzyGlFqSAJWE6l4XaWlNhEA2MpK1LI=,iv:ELpz86ISwFdXUwGitlRxwwXLzUj24lmd563BzKhE08Q=,tag:Z2koWWykmyHiXsantc390A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
