# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: plane-app-secrets
    namespace: business
stringData:
    values.yaml: ENC[AES256_GCM,data:gBu3mkWhiLuFH+T00Y4Sb3phkqxCBGi/P4t0EhTPFha7W1KllnVXfc6BubMAegEtVmoCTsX4li2yPeLntHihQbPA/zTuDtyda8e3v00drVXByL2NdoMnE8wJ1r1oSBIRUwNKJXrIP+Hl+kdsIDr0iPlrADZ7+9XO1wtI+iLlMndkVGHTodFgLDwOk35h9wh4UFIpsKK8KhnA+yzvfU9QWLcLKOSLUHH78Ji2+sKCp1DcsUQwsqb++K0pK4Atrcm+MwbUj/Q6kR3GmpzvVZZ69TZJRST8LwxoLVQ1H+VwvCOQHqSF27WPmuKhqBAkzCUtzxFEOEqhgQHuHtkiIp4IKuZREpZcKdDRKFm/kuAzxNkKA88I6WvLFPKHVRtyEbKfu9JqrYxXgjdQftsghs0UC8Qr6CMxpflfQC6KIC5NXUHLM4o5j7Vo5YB85/vhGutY5gzjVJY/3J9Vk2fP+SLsnxJtr02D3h2NH7GjHxt9MjJ5jUavnA3bRVTXdbu3UYC9cYtSswI/D8Y5Hli4CosHe96ZIk0+BuAX0G9ev4RdkXOFRIG0d452S3rfPz+9Y9jEY1g1lfppIAW6fu+g/acAX8ijwuz+6+7BmHh1/i577PQhKNNSLv+5mtM3juerxFKyMk205JaMElQUj2ONEdC6KXAPjw5ANqT4OHpCP5pnHgRjVV8aPUjoveLKP6ZKJ5mw81bTebNkOs7cOVYpFU+1zWvaRTvQEGB6txgdp+KJucFRtxVax14b64NJwoCFGEGmF1225AU=,iv:+sfOT0KvypLSIRnKPI8zCmGfmV8M1nVK0MvUbH5HYtg=,tag:U3P50wSPTUxG39e6jW8rrQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14j28wpn82nnskt0rzcaqxzwnhx33ardgl640rckvwrys8grphvwsyt4ch2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUjQ2NmtLQ1JKVEgwRkdS
            MVZTUnNZWUsvUS9MVWpwb001bXd3L2lJSlhrCkJFajBHNzVobnRWNU5TV2swYnRO
            dEIyNnRpVVVTK01YWU5wZTRPbGN6Y1EKLS0tIGFwYno0aCtybXBLVFc1L2I5VFlB
            eGJtck1sVEVQMi9nZWgvS3hJTm9KWlUKCUUgCNrIGhAfvkFpfoSbyE8y37MS5Bww
            ET2BH5lqLdq35hGdU0jubOFrk4iLyC88x3YEyuIOjrHdf9eCLfQM/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-15T03:08:41Z"
    mac: ENC[AES256_GCM,data:uailGUqrTUCNnxxlaZlMhj2YOfTiznWUS2X5CuUfFXOvKBsN2n4ibAmbvl18X1avYUYKXNWK2av4G9Z2h6NqLPISBFJv215RL+oM7A9WMwopaCxW6UBHqNu/yhGqWsoEk9xtCJQNFDHf5CzMIWfXL94zq57fhcbkA8lYUDc8ufw=,iv:g/lnO7Z/+Or+mTxrC73x9y5nntVuiC2gys8lHb/0eCY=,tag:WbnsxyPeFtgU9cUzSyBytw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
